// Code generated by ent, DO NOT EDIT.

package dockerevent

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dockerevent type in the database.
	Label = "docker_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldAction holds the string denoting the action field in the database.
	FieldAction = "action"
	// FieldActorID holds the string denoting the actor_id field in the database.
	FieldActorID = "actor_id"
	// FieldActorName holds the string denoting the actor_name field in the database.
	FieldActorName = "actor_name"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldImageOld holds the string denoting the image_old field in the database.
	FieldImageOld = "image_old"
	// FieldImageNew holds the string denoting the image_new field in the database.
	FieldImageNew = "image_new"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the dockerevent in the database.
	Table = "docker_events"
)

// Columns holds all SQL columns for dockerevent fields.
var Columns = []string{
	FieldID,
	FieldEventType,
	FieldAction,
	FieldActorID,
	FieldActorName,
	FieldImage,
	FieldStatus,
	FieldImageOld,
	FieldImageNew,
	FieldPayload,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultEventType holds the default value on creation for the "event_type" field.
	DefaultEventType string
	// DefaultAction holds the default value on creation for the "action" field.
	DefaultAction string
	// DefaultActorID holds the default value on creation for the "actor_id" field.
	DefaultActorID string
	// DefaultActorName holds the default value on creation for the "actor_name" field.
	DefaultActorName string
	// DefaultImage holds the default value on creation for the "image" field.
	DefaultImage string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultImageOld holds the default value on creation for the "image_old" field.
	DefaultImageOld string
	// DefaultImageNew holds the default value on creation for the "image_new" field.
	DefaultImageNew string
	// DefaultPayload holds the default value on creation for the "payload" field.
	DefaultPayload string
)

// OrderOption defines the ordering options for the DockerEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByAction orders the results by the action field.
func ByAction(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAction, opts...).ToFunc()
}

// ByActorID orders the results by the actor_id field.
func ByActorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorID, opts...).ToFunc()
}

// ByActorName orders the results by the actor_name field.
func ByActorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorName, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByImageOld orders the results by the image_old field.
func ByImageOld(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageOld, opts...).ToFunc()
}

// ByImageNew orders the results by the image_new field.
func ByImageNew(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageNew, opts...).ToFunc()
}

// ByPayload orders the results by the payload field.
func ByPayload(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayload, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
