// Code generated by ent, DO NOT EDIT.

package autheliainstance

import (
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldName, v))
}

// ConfigPath applies equality check predicate on the "config_path" field. It's identical to ConfigPathEQ.
func ConfigPath(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldConfigPath, v))
}

// DbPath applies equality check predicate on the "db_path" field. It's identical to DbPathEQ.
func DbPath(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldDbPath, v))
}

// DefaultPolicy applies equality check predicate on the "default_policy" field. It's identical to DefaultPolicyEQ.
func DefaultPolicy(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldDefaultPolicy, v))
}

// Overrides applies equality check predicate on the "overrides" field. It's identical to OverridesEQ.
func Overrides(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldOverrides, v))
}

// AutoSync applies equality check predicate on the "auto_sync" field. It's identical to AutoSyncEQ.
func AutoSync(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldAutoSync, v))
}

// NpmInstanceIds applies equality check predicate on the "npm_instance_ids" field. It's identical to NpmInstanceIdsEQ.
func NpmInstanceIds(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldNpmInstanceIds, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldName, v))
}

// ConfigPathEQ applies the EQ predicate on the "config_path" field.
func ConfigPathEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldConfigPath, v))
}

// ConfigPathNEQ applies the NEQ predicate on the "config_path" field.
func ConfigPathNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldConfigPath, v))
}

// ConfigPathIn applies the In predicate on the "config_path" field.
func ConfigPathIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldConfigPath, vs...))
}

// ConfigPathNotIn applies the NotIn predicate on the "config_path" field.
func ConfigPathNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldConfigPath, vs...))
}

// ConfigPathGT applies the GT predicate on the "config_path" field.
func ConfigPathGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldConfigPath, v))
}

// ConfigPathGTE applies the GTE predicate on the "config_path" field.
func ConfigPathGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldConfigPath, v))
}

// ConfigPathLT applies the LT predicate on the "config_path" field.
func ConfigPathLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldConfigPath, v))
}

// ConfigPathLTE applies the LTE predicate on the "config_path" field.
func ConfigPathLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldConfigPath, v))
}

// ConfigPathContains applies the Contains predicate on the "config_path" field.
func ConfigPathContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldConfigPath, v))
}

// ConfigPathHasPrefix applies the HasPrefix predicate on the "config_path" field.
func ConfigPathHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldConfigPath, v))
}

// ConfigPathHasSuffix applies the HasSuffix predicate on the "config_path" field.
func ConfigPathHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldConfigPath, v))
}

// ConfigPathEqualFold applies the EqualFold predicate on the "config_path" field.
func ConfigPathEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldConfigPath, v))
}

// ConfigPathContainsFold applies the ContainsFold predicate on the "config_path" field.
func ConfigPathContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldConfigPath, v))
}

// DbPathEQ applies the EQ predicate on the "db_path" field.
func DbPathEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldDbPath, v))
}

// DbPathNEQ applies the NEQ predicate on the "db_path" field.
func DbPathNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldDbPath, v))
}

// DbPathIn applies the In predicate on the "db_path" field.
func DbPathIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldDbPath, vs...))
}

// DbPathNotIn applies the NotIn predicate on the "db_path" field.
func DbPathNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldDbPath, vs...))
}

// DbPathGT applies the GT predicate on the "db_path" field.
func DbPathGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldDbPath, v))
}

// DbPathGTE applies the GTE predicate on the "db_path" field.
func DbPathGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldDbPath, v))
}

// DbPathLT applies the LT predicate on the "db_path" field.
func DbPathLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldDbPath, v))
}

// DbPathLTE applies the LTE predicate on the "db_path" field.
func DbPathLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldDbPath, v))
}

// DbPathContains applies the Contains predicate on the "db_path" field.
func DbPathContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldDbPath, v))
}

// DbPathHasPrefix applies the HasPrefix predicate on the "db_path" field.
func DbPathHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldDbPath, v))
}

// DbPathHasSuffix applies the HasSuffix predicate on the "db_path" field.
func DbPathHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldDbPath, v))
}

// DbPathIsNil applies the IsNil predicate on the "db_path" field.
func DbPathIsNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIsNull(FieldDbPath))
}

// DbPathNotNil applies the NotNil predicate on the "db_path" field.
func DbPathNotNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotNull(FieldDbPath))
}

// DbPathEqualFold applies the EqualFold predicate on the "db_path" field.
func DbPathEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldDbPath, v))
}

// DbPathContainsFold applies the ContainsFold predicate on the "db_path" field.
func DbPathContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldDbPath, v))
}

// DefaultPolicyEQ applies the EQ predicate on the "default_policy" field.
func DefaultPolicyEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldDefaultPolicy, v))
}

// DefaultPolicyNEQ applies the NEQ predicate on the "default_policy" field.
func DefaultPolicyNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldDefaultPolicy, v))
}

// DefaultPolicyIn applies the In predicate on the "default_policy" field.
func DefaultPolicyIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldDefaultPolicy, vs...))
}

// DefaultPolicyNotIn applies the NotIn predicate on the "default_policy" field.
func DefaultPolicyNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldDefaultPolicy, vs...))
}

// DefaultPolicyGT applies the GT predicate on the "default_policy" field.
func DefaultPolicyGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldDefaultPolicy, v))
}

// DefaultPolicyGTE applies the GTE predicate on the "default_policy" field.
func DefaultPolicyGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldDefaultPolicy, v))
}

// DefaultPolicyLT applies the LT predicate on the "default_policy" field.
func DefaultPolicyLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldDefaultPolicy, v))
}

// DefaultPolicyLTE applies the LTE predicate on the "default_policy" field.
func DefaultPolicyLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldDefaultPolicy, v))
}

// DefaultPolicyContains applies the Contains predicate on the "default_policy" field.
func DefaultPolicyContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldDefaultPolicy, v))
}

// DefaultPolicyHasPrefix applies the HasPrefix predicate on the "default_policy" field.
func DefaultPolicyHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldDefaultPolicy, v))
}

// DefaultPolicyHasSuffix applies the HasSuffix predicate on the "default_policy" field.
func DefaultPolicyHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldDefaultPolicy, v))
}

// DefaultPolicyEqualFold applies the EqualFold predicate on the "default_policy" field.
func DefaultPolicyEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldDefaultPolicy, v))
}

// DefaultPolicyContainsFold applies the ContainsFold predicate on the "default_policy" field.
func DefaultPolicyContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldDefaultPolicy, v))
}

// OverridesEQ applies the EQ predicate on the "overrides" field.
func OverridesEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldOverrides, v))
}

// OverridesNEQ applies the NEQ predicate on the "overrides" field.
func OverridesNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldOverrides, v))
}

// OverridesIn applies the In predicate on the "overrides" field.
func OverridesIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldOverrides, vs...))
}

// OverridesNotIn applies the NotIn predicate on the "overrides" field.
func OverridesNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldOverrides, vs...))
}

// OverridesGT applies the GT predicate on the "overrides" field.
func OverridesGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldOverrides, v))
}

// OverridesGTE applies the GTE predicate on the "overrides" field.
func OverridesGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldOverrides, v))
}

// OverridesLT applies the LT predicate on the "overrides" field.
func OverridesLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldOverrides, v))
}

// OverridesLTE applies the LTE predicate on the "overrides" field.
func OverridesLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldOverrides, v))
}

// OverridesContains applies the Contains predicate on the "overrides" field.
func OverridesContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldOverrides, v))
}

// OverridesHasPrefix applies the HasPrefix predicate on the "overrides" field.
func OverridesHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldOverrides, v))
}

// OverridesHasSuffix applies the HasSuffix predicate on the "overrides" field.
func OverridesHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldOverrides, v))
}

// OverridesIsNil applies the IsNil predicate on the "overrides" field.
func OverridesIsNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIsNull(FieldOverrides))
}

// OverridesNotNil applies the NotNil predicate on the "overrides" field.
func OverridesNotNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotNull(FieldOverrides))
}

// OverridesEqualFold applies the EqualFold predicate on the "overrides" field.
func OverridesEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldOverrides, v))
}

// OverridesContainsFold applies the ContainsFold predicate on the "overrides" field.
func OverridesContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldOverrides, v))
}

// AutoSyncEQ applies the EQ predicate on the "auto_sync" field.
func AutoSyncEQ(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldAutoSync, v))
}

// AutoSyncNEQ applies the NEQ predicate on the "auto_sync" field.
func AutoSyncNEQ(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldAutoSync, v))
}

// NpmInstanceIdsEQ applies the EQ predicate on the "npm_instance_ids" field.
func NpmInstanceIdsEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsNEQ applies the NEQ predicate on the "npm_instance_ids" field.
func NpmInstanceIdsNEQ(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsIn applies the In predicate on the "npm_instance_ids" field.
func NpmInstanceIdsIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldNpmInstanceIds, vs...))
}

// NpmInstanceIdsNotIn applies the NotIn predicate on the "npm_instance_ids" field.
func NpmInstanceIdsNotIn(vs ...string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldNpmInstanceIds, vs...))
}

// NpmInstanceIdsGT applies the GT predicate on the "npm_instance_ids" field.
func NpmInstanceIdsGT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsGTE applies the GTE predicate on the "npm_instance_ids" field.
func NpmInstanceIdsGTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsLT applies the LT predicate on the "npm_instance_ids" field.
func NpmInstanceIdsLT(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsLTE applies the LTE predicate on the "npm_instance_ids" field.
func NpmInstanceIdsLTE(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsContains applies the Contains predicate on the "npm_instance_ids" field.
func NpmInstanceIdsContains(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContains(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsHasPrefix applies the HasPrefix predicate on the "npm_instance_ids" field.
func NpmInstanceIdsHasPrefix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasPrefix(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsHasSuffix applies the HasSuffix predicate on the "npm_instance_ids" field.
func NpmInstanceIdsHasSuffix(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldHasSuffix(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsIsNil applies the IsNil predicate on the "npm_instance_ids" field.
func NpmInstanceIdsIsNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIsNull(FieldNpmInstanceIds))
}

// NpmInstanceIdsNotNil applies the NotNil predicate on the "npm_instance_ids" field.
func NpmInstanceIdsNotNil() predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotNull(FieldNpmInstanceIds))
}

// NpmInstanceIdsEqualFold applies the EqualFold predicate on the "npm_instance_ids" field.
func NpmInstanceIdsEqualFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEqualFold(FieldNpmInstanceIds, v))
}

// NpmInstanceIdsContainsFold applies the ContainsFold predicate on the "npm_instance_ids" field.
func NpmInstanceIdsContainsFold(v string) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldContainsFold(FieldNpmInstanceIds, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AutheliaInstance) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AutheliaInstance) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AutheliaInstance) predicate.AutheliaInstance {
	return predicate.AutheliaInstance(sql.NotPredicates(p))
}
