// Code generated by ent, DO NOT EDIT.

package syncrun

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the syncrun type in the database.
	Label = "sync_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSource holds the string denoting the source field in the database.
	FieldSource = "source"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldTotalServices holds the string denoting the total_services field in the database.
	FieldTotalServices = "total_services"
	// FieldAdded holds the string denoting the added field in the database.
	FieldAdded = "added"
	// FieldSkipped holds the string denoting the skipped field in the database.
	FieldSkipped = "skipped"
	// FieldFailed holds the string denoting the failed field in the database.
	FieldFailed = "failed"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldDryRun holds the string denoting the dry_run field in the database.
	FieldDryRun = "dry_run"
	// Table holds the table name of the syncrun in the database.
	Table = "sync_runs"
)

// Columns holds all SQL columns for syncrun fields.
var Columns = []string{
	FieldID,
	FieldSource,
	FieldStatus,
	FieldStartedAt,
	FieldFinishedAt,
	FieldTotalServices,
	FieldAdded,
	FieldSkipped,
	FieldFailed,
	FieldErrorMessage,
	FieldDryRun,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultSource holds the default value on creation for the "source" field.
	DefaultSource string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultTotalServices holds the default value on creation for the "total_services" field.
	DefaultTotalServices int
	// DefaultAdded holds the default value on creation for the "added" field.
	DefaultAdded int
	// DefaultSkipped holds the default value on creation for the "skipped" field.
	DefaultSkipped int
	// DefaultFailed holds the default value on creation for the "failed" field.
	DefaultFailed int
	// DefaultErrorMessage holds the default value on creation for the "error_message" field.
	DefaultErrorMessage string
	// DefaultDryRun holds the default value on creation for the "dry_run" field.
	DefaultDryRun bool
)

// OrderOption defines the ordering options for the SyncRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySource orders the results by the source field.
func BySource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSource, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByTotalServices orders the results by the total_services field.
func ByTotalServices(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalServices, opts...).ToFunc()
}

// ByAdded orders the results by the added field.
func ByAdded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdded, opts...).ToFunc()
}

// BySkipped orders the results by the skipped field.
func BySkipped(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSkipped, opts...).ToFunc()
}

// ByFailed orders the results by the failed field.
func ByFailed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailed, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByDryRun orders the results by the dry_run field.
func ByDryRun(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDryRun, opts...).ToFunc()
}
