// Code generated by ent, DO NOT EDIT.

package syncrun

import (
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldID, id))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldSource, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldStatus, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// TotalServices applies equality check predicate on the "total_services" field. It's identical to TotalServicesEQ.
func TotalServices(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldTotalServices, v))
}

// Added applies equality check predicate on the "added" field. It's identical to AddedEQ.
func Added(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldAdded, v))
}

// Skipped applies equality check predicate on the "skipped" field. It's identical to SkippedEQ.
func Skipped(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldSkipped, v))
}

// Failed applies equality check predicate on the "failed" field. It's identical to FailedEQ.
func Failed(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldFailed, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldErrorMessage, v))
}

// DryRun applies equality check predicate on the "dry_run" field. It's identical to DryRunEQ.
func DryRun(v bool) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldDryRun, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContainsFold(FieldSource, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContainsFold(FieldStatus, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotNull(FieldFinishedAt))
}

// TotalServicesEQ applies the EQ predicate on the "total_services" field.
func TotalServicesEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldTotalServices, v))
}

// TotalServicesNEQ applies the NEQ predicate on the "total_services" field.
func TotalServicesNEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldTotalServices, v))
}

// TotalServicesIn applies the In predicate on the "total_services" field.
func TotalServicesIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldTotalServices, vs...))
}

// TotalServicesNotIn applies the NotIn predicate on the "total_services" field.
func TotalServicesNotIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldTotalServices, vs...))
}

// TotalServicesGT applies the GT predicate on the "total_services" field.
func TotalServicesGT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldTotalServices, v))
}

// TotalServicesGTE applies the GTE predicate on the "total_services" field.
func TotalServicesGTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldTotalServices, v))
}

// TotalServicesLT applies the LT predicate on the "total_services" field.
func TotalServicesLT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldTotalServices, v))
}

// TotalServicesLTE applies the LTE predicate on the "total_services" field.
func TotalServicesLTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldTotalServices, v))
}

// AddedEQ applies the EQ predicate on the "added" field.
func AddedEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldAdded, v))
}

// AddedNEQ applies the NEQ predicate on the "added" field.
func AddedNEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldAdded, v))
}

// AddedIn applies the In predicate on the "added" field.
func AddedIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldAdded, vs...))
}

// AddedNotIn applies the NotIn predicate on the "added" field.
func AddedNotIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldAdded, vs...))
}

// AddedGT applies the GT predicate on the "added" field.
func AddedGT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldAdded, v))
}

// AddedGTE applies the GTE predicate on the "added" field.
func AddedGTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldAdded, v))
}

// AddedLT applies the LT predicate on the "added" field.
func AddedLT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldAdded, v))
}

// AddedLTE applies the LTE predicate on the "added" field.
func AddedLTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldAdded, v))
}

// SkippedEQ applies the EQ predicate on the "skipped" field.
func SkippedEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldSkipped, v))
}

// SkippedNEQ applies the NEQ predicate on the "skipped" field.
func SkippedNEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldSkipped, v))
}

// SkippedIn applies the In predicate on the "skipped" field.
func SkippedIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldSkipped, vs...))
}

// SkippedNotIn applies the NotIn predicate on the "skipped" field.
func SkippedNotIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldSkipped, vs...))
}

// SkippedGT applies the GT predicate on the "skipped" field.
func SkippedGT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldSkipped, v))
}

// SkippedGTE applies the GTE predicate on the "skipped" field.
func SkippedGTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldSkipped, v))
}

// SkippedLT applies the LT predicate on the "skipped" field.
func SkippedLT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldSkipped, v))
}

// SkippedLTE applies the LTE predicate on the "skipped" field.
func SkippedLTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldSkipped, v))
}

// FailedEQ applies the EQ predicate on the "failed" field.
func FailedEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldFailed, v))
}

// FailedNEQ applies the NEQ predicate on the "failed" field.
func FailedNEQ(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldFailed, v))
}

// FailedIn applies the In predicate on the "failed" field.
func FailedIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldFailed, vs...))
}

// FailedNotIn applies the NotIn predicate on the "failed" field.
func FailedNotIn(vs ...int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldFailed, vs...))
}

// FailedGT applies the GT predicate on the "failed" field.
func FailedGT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldFailed, v))
}

// FailedGTE applies the GTE predicate on the "failed" field.
func FailedGTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldFailed, v))
}

// FailedLT applies the LT predicate on the "failed" field.
func FailedLT(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldFailed, v))
}

// FailedLTE applies the LTE predicate on the "failed" field.
func FailedLTE(v int) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldFailed, v))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldContainsFold(FieldErrorMessage, v))
}

// DryRunEQ applies the EQ predicate on the "dry_run" field.
func DryRunEQ(v bool) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldEQ(FieldDryRun, v))
}

// DryRunNEQ applies the NEQ predicate on the "dry_run" field.
func DryRunNEQ(v bool) predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNEQ(FieldDryRun, v))
}

// DryRunIsNil applies the IsNil predicate on the "dry_run" field.
func DryRunIsNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldIsNull(FieldDryRun))
}

// DryRunNotNil applies the NotNil predicate on the "dry_run" field.
func DryRunNotNil() predicate.SyncRun {
	return predicate.SyncRun(sql.FieldNotNull(FieldDryRun))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SyncRun) predicate.SyncRun {
	return predicate.SyncRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SyncRun) predicate.SyncRun {
	return predicate.SyncRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SyncRun) predicate.SyncRun {
	return predicate.SyncRun(sql.NotPredicates(p))
}
