// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MonitorsColumns holds the columns for the "monitors" table.
	MonitorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "service_name", Type: field.TypeString},
		{Name: "monitor_type", Type: field.TypeString},
		{Name: "url", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "docker_container", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "kuma_id", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
	}
	// MonitorsTable holds the schema information for the "monitors" table.
	MonitorsTable = &schema.Table{
		Name:       "monitors",
		Columns:    MonitorsColumns,
		PrimaryKey: []*schema.Column{MonitorsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "monitor_name_monitor_type",
				Unique:  true,
				Columns: []*schema.Column{MonitorsColumns[1], MonitorsColumns[3]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "settings_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[1]},
			},
		},
	}
	// SyncRunsColumns holds the columns for the "sync_runs" table.
	SyncRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "source", Type: field.TypeString, Default: "docker"},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "total_services", Type: field.TypeInt, Default: 0},
		{Name: "added", Type: field.TypeInt, Default: 0},
		{Name: "skipped", Type: field.TypeInt, Default: 0},
		{Name: "failed", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// SyncRunsTable holds the schema information for the "sync_runs" table.
	SyncRunsTable = &schema.Table{
		Name:       "sync_runs",
		Columns:    SyncRunsColumns,
		PrimaryKey: []*schema.Column{SyncRunsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MonitorsTable,
		SettingsTable,
		SyncRunsTable,
	}
)

func init() {
}
