// Code generated by ent, DO NOT EDIT.

package servicelink

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the servicelink type in the database.
	Label = "service_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServiceName holds the string denoting the service_name field in the database.
	FieldServiceName = "service_name"
	// FieldNpmInstanceID holds the string denoting the npm_instance_id field in the database.
	FieldNpmInstanceID = "npm_instance_id"
	// FieldNpmHostName holds the string denoting the npm_host_name field in the database.
	FieldNpmHostName = "npm_host_name"
	// FieldNpmDetails holds the string denoting the npm_details field in the database.
	FieldNpmDetails = "npm_details"
	// FieldKumaInstanceID holds the string denoting the kuma_instance_id field in the database.
	FieldKumaInstanceID = "kuma_instance_id"
	// FieldKumaMonitorID holds the string denoting the kuma_monitor_id field in the database.
	FieldKumaMonitorID = "kuma_monitor_id"
	// FieldKumaMonitorName holds the string denoting the kuma_monitor_name field in the database.
	FieldKumaMonitorName = "kuma_monitor_name"
	// FieldKumaDetails holds the string denoting the kuma_details field in the database.
	FieldKumaDetails = "kuma_details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the servicelink in the database.
	Table = "service_links"
)

// Columns holds all SQL columns for servicelink fields.
var Columns = []string{
	FieldID,
	FieldServiceName,
	FieldNpmInstanceID,
	FieldNpmHostName,
	FieldNpmDetails,
	FieldKumaInstanceID,
	FieldKumaMonitorID,
	FieldKumaMonitorName,
	FieldKumaDetails,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultNpmInstanceID holds the default value on creation for the "npm_instance_id" field.
	DefaultNpmInstanceID int
	// DefaultNpmHostName holds the default value on creation for the "npm_host_name" field.
	DefaultNpmHostName string
	// DefaultNpmDetails holds the default value on creation for the "npm_details" field.
	DefaultNpmDetails string
	// DefaultKumaInstanceID holds the default value on creation for the "kuma_instance_id" field.
	DefaultKumaInstanceID int
	// DefaultKumaMonitorID holds the default value on creation for the "kuma_monitor_id" field.
	DefaultKumaMonitorID int
	// DefaultKumaMonitorName holds the default value on creation for the "kuma_monitor_name" field.
	DefaultKumaMonitorName string
	// DefaultKumaDetails holds the default value on creation for the "kuma_details" field.
	DefaultKumaDetails string
)

// OrderOption defines the ordering options for the ServiceLink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServiceName orders the results by the service_name field.
func ByServiceName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServiceName, opts...).ToFunc()
}

// ByNpmInstanceID orders the results by the npm_instance_id field.
func ByNpmInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNpmInstanceID, opts...).ToFunc()
}

// ByNpmHostName orders the results by the npm_host_name field.
func ByNpmHostName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNpmHostName, opts...).ToFunc()
}

// ByNpmDetails orders the results by the npm_details field.
func ByNpmDetails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNpmDetails, opts...).ToFunc()
}

// ByKumaInstanceID orders the results by the kuma_instance_id field.
func ByKumaInstanceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKumaInstanceID, opts...).ToFunc()
}

// ByKumaMonitorID orders the results by the kuma_monitor_id field.
func ByKumaMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKumaMonitorID, opts...).ToFunc()
}

// ByKumaMonitorName orders the results by the kuma_monitor_name field.
func ByKumaMonitorName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKumaMonitorName, opts...).ToFunc()
}

// ByKumaDetails orders the results by the kuma_details field.
func ByKumaDetails(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKumaDetails, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
