// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/autheliaalert"
	"synapse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AutheliaAlertDelete is the builder for deleting a AutheliaAlert entity.
type AutheliaAlertDelete struct {
	config
	hooks    []Hook
	mutation *AutheliaAlertMutation
}

// Where appends a list predicates to the AutheliaAlertDelete builder.
func (_d *AutheliaAlertDelete) Where(ps ...predicate.AutheliaAlert) *AutheliaAlertDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AutheliaAlertDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutheliaAlertDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AutheliaAlertDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(autheliaalert.Table, sqlgraph.NewFieldSpec(autheliaalert.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AutheliaAlertDeleteOne is the builder for deleting a single AutheliaAlert entity.
type AutheliaAlertDeleteOne struct {
	_d *AutheliaAlertDelete
}

// Where appends a list predicates to the AutheliaAlertDelete builder.
func (_d *AutheliaAlertDeleteOne) Where(ps ...predicate.AutheliaAlert) *AutheliaAlertDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AutheliaAlertDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{autheliaalert.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutheliaAlertDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
