// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/autheliainstance"
	"synapse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AutheliaInstanceDelete is the builder for deleting a AutheliaInstance entity.
type AutheliaInstanceDelete struct {
	config
	hooks    []Hook
	mutation *AutheliaInstanceMutation
}

// Where appends a list predicates to the AutheliaInstanceDelete builder.
func (_d *AutheliaInstanceDelete) Where(ps ...predicate.AutheliaInstance) *AutheliaInstanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AutheliaInstanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutheliaInstanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AutheliaInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(autheliainstance.Table, sqlgraph.NewFieldSpec(autheliainstance.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AutheliaInstanceDeleteOne is the builder for deleting a single AutheliaInstance entity.
type AutheliaInstanceDeleteOne struct {
	_d *AutheliaInstanceDelete
}

// Where appends a list predicates to the AutheliaInstanceDelete builder.
func (_d *AutheliaInstanceDeleteOne) Where(ps ...predicate.AutheliaInstance) *AutheliaInstanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AutheliaInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{autheliainstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AutheliaInstanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
