// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/autheliainstance"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AutheliaInstance is the model entity for the AutheliaInstance schema.
type AutheliaInstance struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ConfigPath holds the value of the "config_path" field.
	ConfigPath string `json:"config_path,omitempty"`
	// DbPath holds the value of the "db_path" field.
	DbPath string `json:"db_path,omitempty"`
	// DefaultPolicy holds the value of the "default_policy" field.
	DefaultPolicy string `json:"default_policy,omitempty"`
	// Overrides holds the value of the "overrides" field.
	Overrides string `json:"overrides,omitempty"`
	// AutoSync holds the value of the "auto_sync" field.
	AutoSync bool `json:"auto_sync,omitempty"`
	// NpmInstanceIds holds the value of the "npm_instance_ids" field.
	NpmInstanceIds string `json:"npm_instance_ids,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutheliaInstance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autheliainstance.FieldAutoSync, autheliainstance.FieldEnabled:
			values[i] = new(sql.NullBool)
		case autheliainstance.FieldID:
			values[i] = new(sql.NullInt64)
		case autheliainstance.FieldName, autheliainstance.FieldConfigPath, autheliainstance.FieldDbPath, autheliainstance.FieldDefaultPolicy, autheliainstance.FieldOverrides, autheliainstance.FieldNpmInstanceIds:
			values[i] = new(sql.NullString)
		case autheliainstance.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutheliaInstance fields.
func (_m *AutheliaInstance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autheliainstance.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case autheliainstance.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case autheliainstance.FieldConfigPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_path", values[i])
			} else if value.Valid {
				_m.ConfigPath = value.String
			}
		case autheliainstance.FieldDbPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field db_path", values[i])
			} else if value.Valid {
				_m.DbPath = value.String
			}
		case autheliainstance.FieldDefaultPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_policy", values[i])
			} else if value.Valid {
				_m.DefaultPolicy = value.String
			}
		case autheliainstance.FieldOverrides:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field overrides", values[i])
			} else if value.Valid {
				_m.Overrides = value.String
			}
		case autheliainstance.FieldAutoSync:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_sync", values[i])
			} else if value.Valid {
				_m.AutoSync = value.Bool
			}
		case autheliainstance.FieldNpmInstanceIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field npm_instance_ids", values[i])
			} else if value.Valid {
				_m.NpmInstanceIds = value.String
			}
		case autheliainstance.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case autheliainstance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutheliaInstance.
// This includes values selected through modifiers, order, etc.
func (_m *AutheliaInstance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AutheliaInstance.
// Note that you need to call AutheliaInstance.Unwrap() before calling this method if this AutheliaInstance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AutheliaInstance) Update() *AutheliaInstanceUpdateOne {
	return NewAutheliaInstanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AutheliaInstance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AutheliaInstance) Unwrap() *AutheliaInstance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutheliaInstance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AutheliaInstance) String() string {
	var builder strings.Builder
	builder.WriteString("AutheliaInstance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("config_path=")
	builder.WriteString(_m.ConfigPath)
	builder.WriteString(", ")
	builder.WriteString("db_path=")
	builder.WriteString(_m.DbPath)
	builder.WriteString(", ")
	builder.WriteString("default_policy=")
	builder.WriteString(_m.DefaultPolicy)
	builder.WriteString(", ")
	builder.WriteString("overrides=")
	builder.WriteString(_m.Overrides)
	builder.WriteString(", ")
	builder.WriteString("auto_sync=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoSync))
	builder.WriteString(", ")
	builder.WriteString("npm_instance_ids=")
	builder.WriteString(_m.NpmInstanceIds)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AutheliaInstances is a parsable slice of AutheliaInstance.
type AutheliaInstances []*AutheliaInstance
