// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/autheliaalert"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AutheliaAlert is the model entity for the AutheliaAlert schema.
type AutheliaAlert struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Cname holds the value of the "cname" field.
	Cname string `json:"cname,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity string `json:"severity,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// AutheliaInstanceID holds the value of the "authelia_instance_id" field.
	AutheliaInstanceID int `json:"authelia_instance_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutheliaAlert) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autheliaalert.FieldID, autheliaalert.FieldAutheliaInstanceID:
			values[i] = new(sql.NullInt64)
		case autheliaalert.FieldCname, autheliaalert.FieldMessage, autheliaalert.FieldSeverity, autheliaalert.FieldStatus:
			values[i] = new(sql.NullString)
		case autheliaalert.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutheliaAlert fields.
func (_m *AutheliaAlert) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autheliaalert.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case autheliaalert.FieldCname:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cname", values[i])
			} else if value.Valid {
				_m.Cname = value.String
			}
		case autheliaalert.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case autheliaalert.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = value.String
			}
		case autheliaalert.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case autheliaalert.FieldAutheliaInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field authelia_instance_id", values[i])
			} else if value.Valid {
				_m.AutheliaInstanceID = int(value.Int64)
			}
		case autheliaalert.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutheliaAlert.
// This includes values selected through modifiers, order, etc.
func (_m *AutheliaAlert) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AutheliaAlert.
// Note that you need to call AutheliaAlert.Unwrap() before calling this method if this AutheliaAlert
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AutheliaAlert) Update() *AutheliaAlertUpdateOne {
	return NewAutheliaAlertClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AutheliaAlert entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AutheliaAlert) Unwrap() *AutheliaAlert {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutheliaAlert is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AutheliaAlert) String() string {
	var builder strings.Builder
	builder.WriteString("AutheliaAlert(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("cname=")
	builder.WriteString(_m.Cname)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(_m.Severity)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("authelia_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutheliaInstanceID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AutheliaAlerts is a parsable slice of AutheliaAlert.
type AutheliaAlerts []*AutheliaAlert
