// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/autheliaalert"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AutheliaAlertCreate is the builder for creating a AutheliaAlert entity.
type AutheliaAlertCreate struct {
	config
	mutation *AutheliaAlertMutation
	hooks    []Hook
}

// SetCname sets the "cname" field.
func (_c *AutheliaAlertCreate) SetCname(v string) *AutheliaAlertCreate {
	_c.mutation.SetCname(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *AutheliaAlertCreate) SetMessage(v string) *AutheliaAlertCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetSeverity sets the "severity" field.
func (_c *AutheliaAlertCreate) SetSeverity(v string) *AutheliaAlertCreate {
	_c.mutation.SetSeverity(v)
	return _c
}

// SetNillableSeverity sets the "severity" field if the given value is not nil.
func (_c *AutheliaAlertCreate) SetNillableSeverity(v *string) *AutheliaAlertCreate {
	if v != nil {
		_c.SetSeverity(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AutheliaAlertCreate) SetStatus(v string) *AutheliaAlertCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AutheliaAlertCreate) SetNillableStatus(v *string) *AutheliaAlertCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAutheliaInstanceID sets the "authelia_instance_id" field.
func (_c *AutheliaAlertCreate) SetAutheliaInstanceID(v int) *AutheliaAlertCreate {
	_c.mutation.SetAutheliaInstanceID(v)
	return _c
}

// SetNillableAutheliaInstanceID sets the "authelia_instance_id" field if the given value is not nil.
func (_c *AutheliaAlertCreate) SetNillableAutheliaInstanceID(v *int) *AutheliaAlertCreate {
	if v != nil {
		_c.SetAutheliaInstanceID(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AutheliaAlertCreate) SetCreatedAt(v time.Time) *AutheliaAlertCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// Mutation returns the AutheliaAlertMutation object of the builder.
func (_c *AutheliaAlertCreate) Mutation() *AutheliaAlertMutation {
	return _c.mutation
}

// Save creates the AutheliaAlert in the database.
func (_c *AutheliaAlertCreate) Save(ctx context.Context) (*AutheliaAlert, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AutheliaAlertCreate) SaveX(ctx context.Context) *AutheliaAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AutheliaAlertCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AutheliaAlertCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AutheliaAlertCreate) defaults() {
	if _, ok := _c.mutation.Severity(); !ok {
		v := autheliaalert.DefaultSeverity
		_c.mutation.SetSeverity(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := autheliaalert.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.AutheliaInstanceID(); !ok {
		v := autheliaalert.DefaultAutheliaInstanceID
		_c.mutation.SetAutheliaInstanceID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AutheliaAlertCreate) check() error {
	if _, ok := _c.mutation.Cname(); !ok {
		return &ValidationError{Name: "cname", err: errors.New(`ent: missing required field "AutheliaAlert.cname"`)}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "AutheliaAlert.message"`)}
	}
	if _, ok := _c.mutation.Severity(); !ok {
		return &ValidationError{Name: "severity", err: errors.New(`ent: missing required field "AutheliaAlert.severity"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AutheliaAlert.status"`)}
	}
	if _, ok := _c.mutation.AutheliaInstanceID(); !ok {
		return &ValidationError{Name: "authelia_instance_id", err: errors.New(`ent: missing required field "AutheliaAlert.authelia_instance_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AutheliaAlert.created_at"`)}
	}
	return nil
}

func (_c *AutheliaAlertCreate) sqlSave(ctx context.Context) (*AutheliaAlert, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AutheliaAlertCreate) createSpec() (*AutheliaAlert, *sqlgraph.CreateSpec) {
	var (
		_node = &AutheliaAlert{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(autheliaalert.Table, sqlgraph.NewFieldSpec(autheliaalert.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Cname(); ok {
		_spec.SetField(autheliaalert.FieldCname, field.TypeString, value)
		_node.Cname = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(autheliaalert.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.Severity(); ok {
		_spec.SetField(autheliaalert.FieldSeverity, field.TypeString, value)
		_node.Severity = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(autheliaalert.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.AutheliaInstanceID(); ok {
		_spec.SetField(autheliaalert.FieldAutheliaInstanceID, field.TypeInt, value)
		_node.AutheliaInstanceID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(autheliaalert.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AutheliaAlertCreateBulk is the builder for creating many AutheliaAlert entities in bulk.
type AutheliaAlertCreateBulk struct {
	config
	err      error
	builders []*AutheliaAlertCreate
}

// Save creates the AutheliaAlert entities in the database.
func (_c *AutheliaAlertCreateBulk) Save(ctx context.Context) ([]*AutheliaAlert, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AutheliaAlert, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AutheliaAlertMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AutheliaAlertCreateBulk) SaveX(ctx context.Context) []*AutheliaAlert {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AutheliaAlertCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AutheliaAlertCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
