// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"synapse/ent/migrate"

	"synapse/ent/autheliaalert"
	"synapse/ent/kumainstance"
	"synapse/ent/monitor"
	"synapse/ent/settings"
	"synapse/ent/syncrun"
	"synapse/ent/tempaccess"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AutheliaAlert is the client for interacting with the AutheliaAlert builders.
	AutheliaAlert *AutheliaAlertClient
	// KumaInstance is the client for interacting with the KumaInstance builders.
	KumaInstance *KumaInstanceClient
	// Monitor is the client for interacting with the Monitor builders.
	Monitor *MonitorClient
	// Settings is the client for interacting with the Settings builders.
	Settings *SettingsClient
	// SyncRun is the client for interacting with the SyncRun builders.
	SyncRun *SyncRunClient
	// TempAccess is the client for interacting with the TempAccess builders.
	TempAccess *TempAccessClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AutheliaAlert = NewAutheliaAlertClient(c.config)
	c.KumaInstance = NewKumaInstanceClient(c.config)
	c.Monitor = NewMonitorClient(c.config)
	c.Settings = NewSettingsClient(c.config)
	c.SyncRun = NewSyncRunClient(c.config)
	c.TempAccess = NewTempAccessClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AutheliaAlert: NewAutheliaAlertClient(cfg),
		KumaInstance:  NewKumaInstanceClient(cfg),
		Monitor:       NewMonitorClient(cfg),
		Settings:      NewSettingsClient(cfg),
		SyncRun:       NewSyncRunClient(cfg),
		TempAccess:    NewTempAccessClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		AutheliaAlert: NewAutheliaAlertClient(cfg),
		KumaInstance:  NewKumaInstanceClient(cfg),
		Monitor:       NewMonitorClient(cfg),
		Settings:      NewSettingsClient(cfg),
		SyncRun:       NewSyncRunClient(cfg),
		TempAccess:    NewTempAccessClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AutheliaAlert.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.AutheliaAlert, c.KumaInstance, c.Monitor, c.Settings, c.SyncRun, c.TempAccess,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.AutheliaAlert, c.KumaInstance, c.Monitor, c.Settings, c.SyncRun, c.TempAccess,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AutheliaAlertMutation:
		return c.AutheliaAlert.mutate(ctx, m)
	case *KumaInstanceMutation:
		return c.KumaInstance.mutate(ctx, m)
	case *MonitorMutation:
		return c.Monitor.mutate(ctx, m)
	case *SettingsMutation:
		return c.Settings.mutate(ctx, m)
	case *SyncRunMutation:
		return c.SyncRun.mutate(ctx, m)
	case *TempAccessMutation:
		return c.TempAccess.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AutheliaAlertClient is a client for the AutheliaAlert schema.
type AutheliaAlertClient struct {
	config
}

// NewAutheliaAlertClient returns a client for the AutheliaAlert from the given config.
func NewAutheliaAlertClient(c config) *AutheliaAlertClient {
	return &AutheliaAlertClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `autheliaalert.Hooks(f(g(h())))`.
func (c *AutheliaAlertClient) Use(hooks ...Hook) {
	c.hooks.AutheliaAlert = append(c.hooks.AutheliaAlert, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `autheliaalert.Intercept(f(g(h())))`.
func (c *AutheliaAlertClient) Intercept(interceptors ...Interceptor) {
	c.inters.AutheliaAlert = append(c.inters.AutheliaAlert, interceptors...)
}

// Create returns a builder for creating a AutheliaAlert entity.
func (c *AutheliaAlertClient) Create() *AutheliaAlertCreate {
	mutation := newAutheliaAlertMutation(c.config, OpCreate)
	return &AutheliaAlertCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AutheliaAlert entities.
func (c *AutheliaAlertClient) CreateBulk(builders ...*AutheliaAlertCreate) *AutheliaAlertCreateBulk {
	return &AutheliaAlertCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AutheliaAlertClient) MapCreateBulk(slice any, setFunc func(*AutheliaAlertCreate, int)) *AutheliaAlertCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AutheliaAlertCreateBulk{err: fmt.Errorf("calling to AutheliaAlertClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AutheliaAlertCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AutheliaAlertCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AutheliaAlert.
func (c *AutheliaAlertClient) Update() *AutheliaAlertUpdate {
	mutation := newAutheliaAlertMutation(c.config, OpUpdate)
	return &AutheliaAlertUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AutheliaAlertClient) UpdateOne(_m *AutheliaAlert) *AutheliaAlertUpdateOne {
	mutation := newAutheliaAlertMutation(c.config, OpUpdateOne, withAutheliaAlert(_m))
	return &AutheliaAlertUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AutheliaAlertClient) UpdateOneID(id int) *AutheliaAlertUpdateOne {
	mutation := newAutheliaAlertMutation(c.config, OpUpdateOne, withAutheliaAlertID(id))
	return &AutheliaAlertUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AutheliaAlert.
func (c *AutheliaAlertClient) Delete() *AutheliaAlertDelete {
	mutation := newAutheliaAlertMutation(c.config, OpDelete)
	return &AutheliaAlertDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AutheliaAlertClient) DeleteOne(_m *AutheliaAlert) *AutheliaAlertDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AutheliaAlertClient) DeleteOneID(id int) *AutheliaAlertDeleteOne {
	builder := c.Delete().Where(autheliaalert.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AutheliaAlertDeleteOne{builder}
}

// Query returns a query builder for AutheliaAlert.
func (c *AutheliaAlertClient) Query() *AutheliaAlertQuery {
	return &AutheliaAlertQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAutheliaAlert},
		inters: c.Interceptors(),
	}
}

// Get returns a AutheliaAlert entity by its id.
func (c *AutheliaAlertClient) Get(ctx context.Context, id int) (*AutheliaAlert, error) {
	return c.Query().Where(autheliaalert.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AutheliaAlertClient) GetX(ctx context.Context, id int) *AutheliaAlert {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AutheliaAlertClient) Hooks() []Hook {
	return c.hooks.AutheliaAlert
}

// Interceptors returns the client interceptors.
func (c *AutheliaAlertClient) Interceptors() []Interceptor {
	return c.inters.AutheliaAlert
}

func (c *AutheliaAlertClient) mutate(ctx context.Context, m *AutheliaAlertMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AutheliaAlertCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AutheliaAlertUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AutheliaAlertUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AutheliaAlertDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AutheliaAlert mutation op: %q", m.Op())
	}
}

// KumaInstanceClient is a client for the KumaInstance schema.
type KumaInstanceClient struct {
	config
}

// NewKumaInstanceClient returns a client for the KumaInstance from the given config.
func NewKumaInstanceClient(c config) *KumaInstanceClient {
	return &KumaInstanceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `kumainstance.Hooks(f(g(h())))`.
func (c *KumaInstanceClient) Use(hooks ...Hook) {
	c.hooks.KumaInstance = append(c.hooks.KumaInstance, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `kumainstance.Intercept(f(g(h())))`.
func (c *KumaInstanceClient) Intercept(interceptors ...Interceptor) {
	c.inters.KumaInstance = append(c.inters.KumaInstance, interceptors...)
}

// Create returns a builder for creating a KumaInstance entity.
func (c *KumaInstanceClient) Create() *KumaInstanceCreate {
	mutation := newKumaInstanceMutation(c.config, OpCreate)
	return &KumaInstanceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of KumaInstance entities.
func (c *KumaInstanceClient) CreateBulk(builders ...*KumaInstanceCreate) *KumaInstanceCreateBulk {
	return &KumaInstanceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *KumaInstanceClient) MapCreateBulk(slice any, setFunc func(*KumaInstanceCreate, int)) *KumaInstanceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &KumaInstanceCreateBulk{err: fmt.Errorf("calling to KumaInstanceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*KumaInstanceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &KumaInstanceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for KumaInstance.
func (c *KumaInstanceClient) Update() *KumaInstanceUpdate {
	mutation := newKumaInstanceMutation(c.config, OpUpdate)
	return &KumaInstanceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *KumaInstanceClient) UpdateOne(_m *KumaInstance) *KumaInstanceUpdateOne {
	mutation := newKumaInstanceMutation(c.config, OpUpdateOne, withKumaInstance(_m))
	return &KumaInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *KumaInstanceClient) UpdateOneID(id int) *KumaInstanceUpdateOne {
	mutation := newKumaInstanceMutation(c.config, OpUpdateOne, withKumaInstanceID(id))
	return &KumaInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for KumaInstance.
func (c *KumaInstanceClient) Delete() *KumaInstanceDelete {
	mutation := newKumaInstanceMutation(c.config, OpDelete)
	return &KumaInstanceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *KumaInstanceClient) DeleteOne(_m *KumaInstance) *KumaInstanceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *KumaInstanceClient) DeleteOneID(id int) *KumaInstanceDeleteOne {
	builder := c.Delete().Where(kumainstance.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &KumaInstanceDeleteOne{builder}
}

// Query returns a query builder for KumaInstance.
func (c *KumaInstanceClient) Query() *KumaInstanceQuery {
	return &KumaInstanceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeKumaInstance},
		inters: c.Interceptors(),
	}
}

// Get returns a KumaInstance entity by its id.
func (c *KumaInstanceClient) Get(ctx context.Context, id int) (*KumaInstance, error) {
	return c.Query().Where(kumainstance.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *KumaInstanceClient) GetX(ctx context.Context, id int) *KumaInstance {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *KumaInstanceClient) Hooks() []Hook {
	return c.hooks.KumaInstance
}

// Interceptors returns the client interceptors.
func (c *KumaInstanceClient) Interceptors() []Interceptor {
	return c.inters.KumaInstance
}

func (c *KumaInstanceClient) mutate(ctx context.Context, m *KumaInstanceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&KumaInstanceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&KumaInstanceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&KumaInstanceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&KumaInstanceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown KumaInstance mutation op: %q", m.Op())
	}
}

// MonitorClient is a client for the Monitor schema.
type MonitorClient struct {
	config
}

// NewMonitorClient returns a client for the Monitor from the given config.
func NewMonitorClient(c config) *MonitorClient {
	return &MonitorClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `monitor.Hooks(f(g(h())))`.
func (c *MonitorClient) Use(hooks ...Hook) {
	c.hooks.Monitor = append(c.hooks.Monitor, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `monitor.Intercept(f(g(h())))`.
func (c *MonitorClient) Intercept(interceptors ...Interceptor) {
	c.inters.Monitor = append(c.inters.Monitor, interceptors...)
}

// Create returns a builder for creating a Monitor entity.
func (c *MonitorClient) Create() *MonitorCreate {
	mutation := newMonitorMutation(c.config, OpCreate)
	return &MonitorCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Monitor entities.
func (c *MonitorClient) CreateBulk(builders ...*MonitorCreate) *MonitorCreateBulk {
	return &MonitorCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *MonitorClient) MapCreateBulk(slice any, setFunc func(*MonitorCreate, int)) *MonitorCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &MonitorCreateBulk{err: fmt.Errorf("calling to MonitorClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*MonitorCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &MonitorCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Monitor.
func (c *MonitorClient) Update() *MonitorUpdate {
	mutation := newMonitorMutation(c.config, OpUpdate)
	return &MonitorUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MonitorClient) UpdateOne(_m *Monitor) *MonitorUpdateOne {
	mutation := newMonitorMutation(c.config, OpUpdateOne, withMonitor(_m))
	return &MonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MonitorClient) UpdateOneID(id int) *MonitorUpdateOne {
	mutation := newMonitorMutation(c.config, OpUpdateOne, withMonitorID(id))
	return &MonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Monitor.
func (c *MonitorClient) Delete() *MonitorDelete {
	mutation := newMonitorMutation(c.config, OpDelete)
	return &MonitorDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *MonitorClient) DeleteOne(_m *Monitor) *MonitorDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *MonitorClient) DeleteOneID(id int) *MonitorDeleteOne {
	builder := c.Delete().Where(monitor.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MonitorDeleteOne{builder}
}

// Query returns a query builder for Monitor.
func (c *MonitorClient) Query() *MonitorQuery {
	return &MonitorQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeMonitor},
		inters: c.Interceptors(),
	}
}

// Get returns a Monitor entity by its id.
func (c *MonitorClient) Get(ctx context.Context, id int) (*Monitor, error) {
	return c.Query().Where(monitor.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MonitorClient) GetX(ctx context.Context, id int) *Monitor {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MonitorClient) Hooks() []Hook {
	return c.hooks.Monitor
}

// Interceptors returns the client interceptors.
func (c *MonitorClient) Interceptors() []Interceptor {
	return c.inters.Monitor
}

func (c *MonitorClient) mutate(ctx context.Context, m *MonitorMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&MonitorCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&MonitorUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&MonitorUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&MonitorDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Monitor mutation op: %q", m.Op())
	}
}

// SettingsClient is a client for the Settings schema.
type SettingsClient struct {
	config
}

// NewSettingsClient returns a client for the Settings from the given config.
func NewSettingsClient(c config) *SettingsClient {
	return &SettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `settings.Hooks(f(g(h())))`.
func (c *SettingsClient) Use(hooks ...Hook) {
	c.hooks.Settings = append(c.hooks.Settings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `settings.Intercept(f(g(h())))`.
func (c *SettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Settings = append(c.inters.Settings, interceptors...)
}

// Create returns a builder for creating a Settings entity.
func (c *SettingsClient) Create() *SettingsCreate {
	mutation := newSettingsMutation(c.config, OpCreate)
	return &SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Settings entities.
func (c *SettingsClient) CreateBulk(builders ...*SettingsCreate) *SettingsCreateBulk {
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SettingsClient) MapCreateBulk(slice any, setFunc func(*SettingsCreate, int)) *SettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SettingsCreateBulk{err: fmt.Errorf("calling to SettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Settings.
func (c *SettingsClient) Update() *SettingsUpdate {
	mutation := newSettingsMutation(c.config, OpUpdate)
	return &SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SettingsClient) UpdateOne(_m *Settings) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettings(_m))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SettingsClient) UpdateOneID(id int) *SettingsUpdateOne {
	mutation := newSettingsMutation(c.config, OpUpdateOne, withSettingsID(id))
	return &SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Settings.
func (c *SettingsClient) Delete() *SettingsDelete {
	mutation := newSettingsMutation(c.config, OpDelete)
	return &SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SettingsClient) DeleteOne(_m *Settings) *SettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SettingsClient) DeleteOneID(id int) *SettingsDeleteOne {
	builder := c.Delete().Where(settings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SettingsDeleteOne{builder}
}

// Query returns a query builder for Settings.
func (c *SettingsClient) Query() *SettingsQuery {
	return &SettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a Settings entity by its id.
func (c *SettingsClient) Get(ctx context.Context, id int) (*Settings, error) {
	return c.Query().Where(settings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SettingsClient) GetX(ctx context.Context, id int) *Settings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SettingsClient) Hooks() []Hook {
	return c.hooks.Settings
}

// Interceptors returns the client interceptors.
func (c *SettingsClient) Interceptors() []Interceptor {
	return c.inters.Settings
}

func (c *SettingsClient) mutate(ctx context.Context, m *SettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Settings mutation op: %q", m.Op())
	}
}

// SyncRunClient is a client for the SyncRun schema.
type SyncRunClient struct {
	config
}

// NewSyncRunClient returns a client for the SyncRun from the given config.
func NewSyncRunClient(c config) *SyncRunClient {
	return &SyncRunClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `syncrun.Hooks(f(g(h())))`.
func (c *SyncRunClient) Use(hooks ...Hook) {
	c.hooks.SyncRun = append(c.hooks.SyncRun, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `syncrun.Intercept(f(g(h())))`.
func (c *SyncRunClient) Intercept(interceptors ...Interceptor) {
	c.inters.SyncRun = append(c.inters.SyncRun, interceptors...)
}

// Create returns a builder for creating a SyncRun entity.
func (c *SyncRunClient) Create() *SyncRunCreate {
	mutation := newSyncRunMutation(c.config, OpCreate)
	return &SyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SyncRun entities.
func (c *SyncRunClient) CreateBulk(builders ...*SyncRunCreate) *SyncRunCreateBulk {
	return &SyncRunCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SyncRunClient) MapCreateBulk(slice any, setFunc func(*SyncRunCreate, int)) *SyncRunCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SyncRunCreateBulk{err: fmt.Errorf("calling to SyncRunClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SyncRunCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SyncRunCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SyncRun.
func (c *SyncRunClient) Update() *SyncRunUpdate {
	mutation := newSyncRunMutation(c.config, OpUpdate)
	return &SyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SyncRunClient) UpdateOne(_m *SyncRun) *SyncRunUpdateOne {
	mutation := newSyncRunMutation(c.config, OpUpdateOne, withSyncRun(_m))
	return &SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SyncRunClient) UpdateOneID(id int) *SyncRunUpdateOne {
	mutation := newSyncRunMutation(c.config, OpUpdateOne, withSyncRunID(id))
	return &SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SyncRun.
func (c *SyncRunClient) Delete() *SyncRunDelete {
	mutation := newSyncRunMutation(c.config, OpDelete)
	return &SyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SyncRunClient) DeleteOne(_m *SyncRun) *SyncRunDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SyncRunClient) DeleteOneID(id int) *SyncRunDeleteOne {
	builder := c.Delete().Where(syncrun.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SyncRunDeleteOne{builder}
}

// Query returns a query builder for SyncRun.
func (c *SyncRunClient) Query() *SyncRunQuery {
	return &SyncRunQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSyncRun},
		inters: c.Interceptors(),
	}
}

// Get returns a SyncRun entity by its id.
func (c *SyncRunClient) Get(ctx context.Context, id int) (*SyncRun, error) {
	return c.Query().Where(syncrun.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SyncRunClient) GetX(ctx context.Context, id int) *SyncRun {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *SyncRunClient) Hooks() []Hook {
	return c.hooks.SyncRun
}

// Interceptors returns the client interceptors.
func (c *SyncRunClient) Interceptors() []Interceptor {
	return c.inters.SyncRun
}

func (c *SyncRunClient) mutate(ctx context.Context, m *SyncRunMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SyncRunCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SyncRunUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SyncRunUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SyncRunDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SyncRun mutation op: %q", m.Op())
	}
}

// TempAccessClient is a client for the TempAccess schema.
type TempAccessClient struct {
	config
}

// NewTempAccessClient returns a client for the TempAccess from the given config.
func NewTempAccessClient(c config) *TempAccessClient {
	return &TempAccessClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tempaccess.Hooks(f(g(h())))`.
func (c *TempAccessClient) Use(hooks ...Hook) {
	c.hooks.TempAccess = append(c.hooks.TempAccess, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tempaccess.Intercept(f(g(h())))`.
func (c *TempAccessClient) Intercept(interceptors ...Interceptor) {
	c.inters.TempAccess = append(c.inters.TempAccess, interceptors...)
}

// Create returns a builder for creating a TempAccess entity.
func (c *TempAccessClient) Create() *TempAccessCreate {
	mutation := newTempAccessMutation(c.config, OpCreate)
	return &TempAccessCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TempAccess entities.
func (c *TempAccessClient) CreateBulk(builders ...*TempAccessCreate) *TempAccessCreateBulk {
	return &TempAccessCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TempAccessClient) MapCreateBulk(slice any, setFunc func(*TempAccessCreate, int)) *TempAccessCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TempAccessCreateBulk{err: fmt.Errorf("calling to TempAccessClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TempAccessCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TempAccessCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TempAccess.
func (c *TempAccessClient) Update() *TempAccessUpdate {
	mutation := newTempAccessMutation(c.config, OpUpdate)
	return &TempAccessUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TempAccessClient) UpdateOne(_m *TempAccess) *TempAccessUpdateOne {
	mutation := newTempAccessMutation(c.config, OpUpdateOne, withTempAccess(_m))
	return &TempAccessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TempAccessClient) UpdateOneID(id int) *TempAccessUpdateOne {
	mutation := newTempAccessMutation(c.config, OpUpdateOne, withTempAccessID(id))
	return &TempAccessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TempAccess.
func (c *TempAccessClient) Delete() *TempAccessDelete {
	mutation := newTempAccessMutation(c.config, OpDelete)
	return &TempAccessDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TempAccessClient) DeleteOne(_m *TempAccess) *TempAccessDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TempAccessClient) DeleteOneID(id int) *TempAccessDeleteOne {
	builder := c.Delete().Where(tempaccess.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TempAccessDeleteOne{builder}
}

// Query returns a query builder for TempAccess.
func (c *TempAccessClient) Query() *TempAccessQuery {
	return &TempAccessQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTempAccess},
		inters: c.Interceptors(),
	}
}

// Get returns a TempAccess entity by its id.
func (c *TempAccessClient) Get(ctx context.Context, id int) (*TempAccess, error) {
	return c.Query().Where(tempaccess.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TempAccessClient) GetX(ctx context.Context, id int) *TempAccess {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TempAccessClient) Hooks() []Hook {
	return c.hooks.TempAccess
}

// Interceptors returns the client interceptors.
func (c *TempAccessClient) Interceptors() []Interceptor {
	return c.inters.TempAccess
}

func (c *TempAccessClient) mutate(ctx context.Context, m *TempAccessMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TempAccessCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TempAccessUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TempAccessUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TempAccessDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TempAccess mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AutheliaAlert, KumaInstance, Monitor, Settings, SyncRun, TempAccess []ent.Hook
	}
	inters struct {
		AutheliaAlert, KumaInstance, Monitor, Settings, SyncRun,
		TempAccess []ent.Interceptor
	}
)
