// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/dockerevent"
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DockerEventUpdate is the builder for updating DockerEvent entities.
type DockerEventUpdate struct {
	config
	hooks    []Hook
	mutation *DockerEventMutation
}

// Where appends a list predicates to the DockerEventUpdate builder.
func (_u *DockerEventUpdate) Where(ps ...predicate.DockerEvent) *DockerEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *DockerEventUpdate) SetEventType(v string) *DockerEventUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableEventType(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *DockerEventUpdate) SetAction(v string) *DockerEventUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableAction(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *DockerEventUpdate) SetActorID(v string) *DockerEventUpdate {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableActorID(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *DockerEventUpdate) ClearActorID() *DockerEventUpdate {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *DockerEventUpdate) SetActorName(v string) *DockerEventUpdate {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableActorName(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// ClearActorName clears the value of the "actor_name" field.
func (_u *DockerEventUpdate) ClearActorName() *DockerEventUpdate {
	_u.mutation.ClearActorName()
	return _u
}

// SetImage sets the "image" field.
func (_u *DockerEventUpdate) SetImage(v string) *DockerEventUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableImage(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DockerEventUpdate) ClearImage() *DockerEventUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DockerEventUpdate) SetStatus(v string) *DockerEventUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableStatus(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DockerEventUpdate) ClearStatus() *DockerEventUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetImageOld sets the "image_old" field.
func (_u *DockerEventUpdate) SetImageOld(v string) *DockerEventUpdate {
	_u.mutation.SetImageOld(v)
	return _u
}

// SetNillableImageOld sets the "image_old" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableImageOld(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetImageOld(*v)
	}
	return _u
}

// ClearImageOld clears the value of the "image_old" field.
func (_u *DockerEventUpdate) ClearImageOld() *DockerEventUpdate {
	_u.mutation.ClearImageOld()
	return _u
}

// SetImageNew sets the "image_new" field.
func (_u *DockerEventUpdate) SetImageNew(v string) *DockerEventUpdate {
	_u.mutation.SetImageNew(v)
	return _u
}

// SetNillableImageNew sets the "image_new" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableImageNew(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetImageNew(*v)
	}
	return _u
}

// ClearImageNew clears the value of the "image_new" field.
func (_u *DockerEventUpdate) ClearImageNew() *DockerEventUpdate {
	_u.mutation.ClearImageNew()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DockerEventUpdate) SetPayload(v string) *DockerEventUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillablePayload(v *string) *DockerEventUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *DockerEventUpdate) ClearPayload() *DockerEventUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DockerEventUpdate) SetCreatedAt(v time.Time) *DockerEventUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DockerEventUpdate) SetNillableCreatedAt(v *time.Time) *DockerEventUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DockerEventMutation object of the builder.
func (_u *DockerEventUpdate) Mutation() *DockerEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DockerEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DockerEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DockerEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DockerEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DockerEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dockerevent.Table, dockerevent.Columns, sqlgraph.NewFieldSpec(dockerevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(dockerevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(dockerevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(dockerevent.FieldActorID, field.TypeString, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(dockerevent.FieldActorID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(dockerevent.FieldActorName, field.TypeString, value)
	}
	if _u.mutation.ActorNameCleared() {
		_spec.ClearField(dockerevent.FieldActorName, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(dockerevent.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(dockerevent.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dockerevent.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dockerevent.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ImageOld(); ok {
		_spec.SetField(dockerevent.FieldImageOld, field.TypeString, value)
	}
	if _u.mutation.ImageOldCleared() {
		_spec.ClearField(dockerevent.FieldImageOld, field.TypeString)
	}
	if value, ok := _u.mutation.ImageNew(); ok {
		_spec.SetField(dockerevent.FieldImageNew, field.TypeString, value)
	}
	if _u.mutation.ImageNewCleared() {
		_spec.ClearField(dockerevent.FieldImageNew, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(dockerevent.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(dockerevent.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dockerevent.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dockerevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DockerEventUpdateOne is the builder for updating a single DockerEvent entity.
type DockerEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DockerEventMutation
}

// SetEventType sets the "event_type" field.
func (_u *DockerEventUpdateOne) SetEventType(v string) *DockerEventUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableEventType(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *DockerEventUpdateOne) SetAction(v string) *DockerEventUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableAction(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *DockerEventUpdateOne) SetActorID(v string) *DockerEventUpdateOne {
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableActorID(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *DockerEventUpdateOne) ClearActorID() *DockerEventUpdateOne {
	_u.mutation.ClearActorID()
	return _u
}

// SetActorName sets the "actor_name" field.
func (_u *DockerEventUpdateOne) SetActorName(v string) *DockerEventUpdateOne {
	_u.mutation.SetActorName(v)
	return _u
}

// SetNillableActorName sets the "actor_name" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableActorName(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetActorName(*v)
	}
	return _u
}

// ClearActorName clears the value of the "actor_name" field.
func (_u *DockerEventUpdateOne) ClearActorName() *DockerEventUpdateOne {
	_u.mutation.ClearActorName()
	return _u
}

// SetImage sets the "image" field.
func (_u *DockerEventUpdateOne) SetImage(v string) *DockerEventUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableImage(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DockerEventUpdateOne) ClearImage() *DockerEventUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *DockerEventUpdateOne) SetStatus(v string) *DockerEventUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableStatus(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *DockerEventUpdateOne) ClearStatus() *DockerEventUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetImageOld sets the "image_old" field.
func (_u *DockerEventUpdateOne) SetImageOld(v string) *DockerEventUpdateOne {
	_u.mutation.SetImageOld(v)
	return _u
}

// SetNillableImageOld sets the "image_old" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableImageOld(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetImageOld(*v)
	}
	return _u
}

// ClearImageOld clears the value of the "image_old" field.
func (_u *DockerEventUpdateOne) ClearImageOld() *DockerEventUpdateOne {
	_u.mutation.ClearImageOld()
	return _u
}

// SetImageNew sets the "image_new" field.
func (_u *DockerEventUpdateOne) SetImageNew(v string) *DockerEventUpdateOne {
	_u.mutation.SetImageNew(v)
	return _u
}

// SetNillableImageNew sets the "image_new" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableImageNew(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetImageNew(*v)
	}
	return _u
}

// ClearImageNew clears the value of the "image_new" field.
func (_u *DockerEventUpdateOne) ClearImageNew() *DockerEventUpdateOne {
	_u.mutation.ClearImageNew()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *DockerEventUpdateOne) SetPayload(v string) *DockerEventUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillablePayload(v *string) *DockerEventUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *DockerEventUpdateOne) ClearPayload() *DockerEventUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *DockerEventUpdateOne) SetCreatedAt(v time.Time) *DockerEventUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *DockerEventUpdateOne) SetNillableCreatedAt(v *time.Time) *DockerEventUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the DockerEventMutation object of the builder.
func (_u *DockerEventUpdateOne) Mutation() *DockerEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the DockerEventUpdate builder.
func (_u *DockerEventUpdateOne) Where(ps ...predicate.DockerEvent) *DockerEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DockerEventUpdateOne) Select(field string, fields ...string) *DockerEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DockerEvent entity.
func (_u *DockerEventUpdateOne) Save(ctx context.Context) (*DockerEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DockerEventUpdateOne) SaveX(ctx context.Context) *DockerEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DockerEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DockerEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *DockerEventUpdateOne) sqlSave(ctx context.Context) (_node *DockerEvent, err error) {
	_spec := sqlgraph.NewUpdateSpec(dockerevent.Table, dockerevent.Columns, sqlgraph.NewFieldSpec(dockerevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DockerEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dockerevent.FieldID)
		for _, f := range fields {
			if !dockerevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dockerevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(dockerevent.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(dockerevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(dockerevent.FieldActorID, field.TypeString, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(dockerevent.FieldActorID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorName(); ok {
		_spec.SetField(dockerevent.FieldActorName, field.TypeString, value)
	}
	if _u.mutation.ActorNameCleared() {
		_spec.ClearField(dockerevent.FieldActorName, field.TypeString)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(dockerevent.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(dockerevent.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dockerevent.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(dockerevent.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ImageOld(); ok {
		_spec.SetField(dockerevent.FieldImageOld, field.TypeString, value)
	}
	if _u.mutation.ImageOldCleared() {
		_spec.ClearField(dockerevent.FieldImageOld, field.TypeString)
	}
	if value, ok := _u.mutation.ImageNew(); ok {
		_spec.SetField(dockerevent.FieldImageNew, field.TypeString, value)
	}
	if _u.mutation.ImageNewCleared() {
		_spec.ClearField(dockerevent.FieldImageNew, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(dockerevent.FieldPayload, field.TypeString, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(dockerevent.FieldPayload, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(dockerevent.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &DockerEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dockerevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
