// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/dockerevent"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// DockerEvent is the model entity for the DockerEvent schema.
type DockerEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID string `json:"actor_id,omitempty"`
	// ActorName holds the value of the "actor_name" field.
	ActorName string `json:"actor_name,omitempty"`
	// Image holds the value of the "image" field.
	Image string `json:"image,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ImageOld holds the value of the "image_old" field.
	ImageOld string `json:"image_old,omitempty"`
	// ImageNew holds the value of the "image_new" field.
	ImageNew string `json:"image_new,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload string `json:"payload,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DockerEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dockerevent.FieldID:
			values[i] = new(sql.NullInt64)
		case dockerevent.FieldEventType, dockerevent.FieldAction, dockerevent.FieldActorID, dockerevent.FieldActorName, dockerevent.FieldImage, dockerevent.FieldStatus, dockerevent.FieldImageOld, dockerevent.FieldImageNew, dockerevent.FieldPayload:
			values[i] = new(sql.NullString)
		case dockerevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DockerEvent fields.
func (_m *DockerEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dockerevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case dockerevent.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case dockerevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case dockerevent.FieldActorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = value.String
			}
		case dockerevent.FieldActorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_name", values[i])
			} else if value.Valid {
				_m.ActorName = value.String
			}
		case dockerevent.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case dockerevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case dockerevent.FieldImageOld:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_old", values[i])
			} else if value.Valid {
				_m.ImageOld = value.String
			}
		case dockerevent.FieldImageNew:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_new", values[i])
			} else if value.Valid {
				_m.ImageNew = value.String
			}
		case dockerevent.FieldPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value.Valid {
				_m.Payload = value.String
			}
		case dockerevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DockerEvent.
// This includes values selected through modifiers, order, etc.
func (_m *DockerEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DockerEvent.
// Note that you need to call DockerEvent.Unwrap() before calling this method if this DockerEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DockerEvent) Update() *DockerEventUpdateOne {
	return NewDockerEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DockerEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DockerEvent) Unwrap() *DockerEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DockerEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DockerEvent) String() string {
	var builder strings.Builder
	builder.WriteString("DockerEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("actor_id=")
	builder.WriteString(_m.ActorID)
	builder.WriteString(", ")
	builder.WriteString("actor_name=")
	builder.WriteString(_m.ActorName)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("image_old=")
	builder.WriteString(_m.ImageOld)
	builder.WriteString(", ")
	builder.WriteString("image_new=")
	builder.WriteString(_m.ImageNew)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(_m.Payload)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DockerEvents is a parsable slice of DockerEvent.
type DockerEvents []*DockerEvent
