// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/dockerevent"
	"synapse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DockerEventDelete is the builder for deleting a DockerEvent entity.
type DockerEventDelete struct {
	config
	hooks    []Hook
	mutation *DockerEventMutation
}

// Where appends a list predicates to the DockerEventDelete builder.
func (_d *DockerEventDelete) Where(ps ...predicate.DockerEvent) *DockerEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *DockerEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DockerEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *DockerEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(dockerevent.Table, sqlgraph.NewFieldSpec(dockerevent.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// DockerEventDeleteOne is the builder for deleting a single DockerEvent entity.
type DockerEventDeleteOne struct {
	_d *DockerEventDelete
}

// Where appends a list predicates to the DockerEventDelete builder.
func (_d *DockerEventDeleteOne) Where(ps ...predicate.DockerEvent) *DockerEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *DockerEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{dockerevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *DockerEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
