// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/monitor"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Monitor is the model entity for the Monitor schema.
type Monitor struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// ServiceName holds the value of the "service_name" field.
	ServiceName string `json:"service_name,omitempty"`
	// MonitorType holds the value of the "monitor_type" field.
	MonitorType string `json:"monitor_type,omitempty"`
	// URL holds the value of the "url" field.
	URL string `json:"url,omitempty"`
	// DockerContainer holds the value of the "docker_container" field.
	DockerContainer string `json:"docker_container,omitempty"`
	// KumaID holds the value of the "kuma_id" field.
	KumaID int `json:"kuma_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Monitor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitor.FieldID, monitor.FieldKumaID:
			values[i] = new(sql.NullInt64)
		case monitor.FieldName, monitor.FieldServiceName, monitor.FieldMonitorType, monitor.FieldURL, monitor.FieldDockerContainer:
			values[i] = new(sql.NullString)
		case monitor.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Monitor fields.
func (_m *Monitor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case monitor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case monitor.FieldServiceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_name", values[i])
			} else if value.Valid {
				_m.ServiceName = value.String
			}
		case monitor.FieldMonitorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_type", values[i])
			} else if value.Valid {
				_m.MonitorType = value.String
			}
		case monitor.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = value.String
			}
		case monitor.FieldDockerContainer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field docker_container", values[i])
			} else if value.Valid {
				_m.DockerContainer = value.String
			}
		case monitor.FieldKumaID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field kuma_id", values[i])
			} else if value.Valid {
				_m.KumaID = int(value.Int64)
			}
		case monitor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Monitor.
// This includes values selected through modifiers, order, etc.
func (_m *Monitor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Monitor.
// Note that you need to call Monitor.Unwrap() before calling this method if this Monitor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Monitor) Update() *MonitorUpdateOne {
	return NewMonitorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Monitor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Monitor) Unwrap() *Monitor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Monitor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Monitor) String() string {
	var builder strings.Builder
	builder.WriteString("Monitor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("service_name=")
	builder.WriteString(_m.ServiceName)
	builder.WriteString(", ")
	builder.WriteString("monitor_type=")
	builder.WriteString(_m.MonitorType)
	builder.WriteString(", ")
	builder.WriteString("url=")
	builder.WriteString(_m.URL)
	builder.WriteString(", ")
	builder.WriteString("docker_container=")
	builder.WriteString(_m.DockerContainer)
	builder.WriteString(", ")
	builder.WriteString("kuma_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KumaID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Monitors is a parsable slice of Monitor.
type Monitors []*Monitor
