// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/monitor"
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MonitorUpdate is the builder for updating Monitor entities.
type MonitorUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorMutation
}

// Where appends a list predicates to the MonitorUpdate builder.
func (_u *MonitorUpdate) Where(ps ...predicate.Monitor) *MonitorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *MonitorUpdate) SetName(v string) *MonitorUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableName(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetServiceName sets the "service_name" field.
func (_u *MonitorUpdate) SetServiceName(v string) *MonitorUpdate {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableServiceName(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// SetMonitorType sets the "monitor_type" field.
func (_u *MonitorUpdate) SetMonitorType(v string) *MonitorUpdate {
	_u.mutation.SetMonitorType(v)
	return _u
}

// SetNillableMonitorType sets the "monitor_type" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableMonitorType(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetMonitorType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *MonitorUpdate) SetURL(v string) *MonitorUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableURL(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MonitorUpdate) ClearURL() *MonitorUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetDockerContainer sets the "docker_container" field.
func (_u *MonitorUpdate) SetDockerContainer(v string) *MonitorUpdate {
	_u.mutation.SetDockerContainer(v)
	return _u
}

// SetNillableDockerContainer sets the "docker_container" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableDockerContainer(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetDockerContainer(*v)
	}
	return _u
}

// ClearDockerContainer clears the value of the "docker_container" field.
func (_u *MonitorUpdate) ClearDockerContainer() *MonitorUpdate {
	_u.mutation.ClearDockerContainer()
	return _u
}

// SetKumaID sets the "kuma_id" field.
func (_u *MonitorUpdate) SetKumaID(v int) *MonitorUpdate {
	_u.mutation.ResetKumaID()
	_u.mutation.SetKumaID(v)
	return _u
}

// SetNillableKumaID sets the "kuma_id" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableKumaID(v *int) *MonitorUpdate {
	if v != nil {
		_u.SetKumaID(*v)
	}
	return _u
}

// AddKumaID adds value to the "kuma_id" field.
func (_u *MonitorUpdate) AddKumaID(v int) *MonitorUpdate {
	_u.mutation.AddKumaID(v)
	return _u
}

// SetKumaInstanceID sets the "kuma_instance_id" field.
func (_u *MonitorUpdate) SetKumaInstanceID(v int) *MonitorUpdate {
	_u.mutation.ResetKumaInstanceID()
	_u.mutation.SetKumaInstanceID(v)
	return _u
}

// SetNillableKumaInstanceID sets the "kuma_instance_id" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableKumaInstanceID(v *int) *MonitorUpdate {
	if v != nil {
		_u.SetKumaInstanceID(*v)
	}
	return _u
}

// AddKumaInstanceID adds value to the "kuma_instance_id" field.
func (_u *MonitorUpdate) AddKumaInstanceID(v int) *MonitorUpdate {
	_u.mutation.AddKumaInstanceID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MonitorUpdate) SetCreatedAt(v time.Time) *MonitorUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableCreatedAt(v *time.Time) *MonitorUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MonitorMutation object of the builder.
func (_u *MonitorUpdate) Mutation() *MonitorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MonitorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MonitorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MonitorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(monitor.Table, monitor.Columns, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(monitor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(monitor.FieldServiceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonitorType(); ok {
		_spec.SetField(monitor.FieldMonitorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(monitor.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(monitor.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.DockerContainer(); ok {
		_spec.SetField(monitor.FieldDockerContainer, field.TypeString, value)
	}
	if _u.mutation.DockerContainerCleared() {
		_spec.ClearField(monitor.FieldDockerContainer, field.TypeString)
	}
	if value, ok := _u.mutation.KumaID(); ok {
		_spec.SetField(monitor.FieldKumaID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaID(); ok {
		_spec.AddField(monitor.FieldKumaID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaInstanceID(); ok {
		_spec.SetField(monitor.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaInstanceID(); ok {
		_spec.AddField(monitor.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(monitor.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MonitorUpdateOne is the builder for updating a single Monitor entity.
type MonitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorMutation
}

// SetName sets the "name" field.
func (_u *MonitorUpdateOne) SetName(v string) *MonitorUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableName(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetServiceName sets the "service_name" field.
func (_u *MonitorUpdateOne) SetServiceName(v string) *MonitorUpdateOne {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableServiceName(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// SetMonitorType sets the "monitor_type" field.
func (_u *MonitorUpdateOne) SetMonitorType(v string) *MonitorUpdateOne {
	_u.mutation.SetMonitorType(v)
	return _u
}

// SetNillableMonitorType sets the "monitor_type" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableMonitorType(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetMonitorType(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *MonitorUpdateOne) SetURL(v string) *MonitorUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableURL(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *MonitorUpdateOne) ClearURL() *MonitorUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetDockerContainer sets the "docker_container" field.
func (_u *MonitorUpdateOne) SetDockerContainer(v string) *MonitorUpdateOne {
	_u.mutation.SetDockerContainer(v)
	return _u
}

// SetNillableDockerContainer sets the "docker_container" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableDockerContainer(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetDockerContainer(*v)
	}
	return _u
}

// ClearDockerContainer clears the value of the "docker_container" field.
func (_u *MonitorUpdateOne) ClearDockerContainer() *MonitorUpdateOne {
	_u.mutation.ClearDockerContainer()
	return _u
}

// SetKumaID sets the "kuma_id" field.
func (_u *MonitorUpdateOne) SetKumaID(v int) *MonitorUpdateOne {
	_u.mutation.ResetKumaID()
	_u.mutation.SetKumaID(v)
	return _u
}

// SetNillableKumaID sets the "kuma_id" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableKumaID(v *int) *MonitorUpdateOne {
	if v != nil {
		_u.SetKumaID(*v)
	}
	return _u
}

// AddKumaID adds value to the "kuma_id" field.
func (_u *MonitorUpdateOne) AddKumaID(v int) *MonitorUpdateOne {
	_u.mutation.AddKumaID(v)
	return _u
}

// SetKumaInstanceID sets the "kuma_instance_id" field.
func (_u *MonitorUpdateOne) SetKumaInstanceID(v int) *MonitorUpdateOne {
	_u.mutation.ResetKumaInstanceID()
	_u.mutation.SetKumaInstanceID(v)
	return _u
}

// SetNillableKumaInstanceID sets the "kuma_instance_id" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableKumaInstanceID(v *int) *MonitorUpdateOne {
	if v != nil {
		_u.SetKumaInstanceID(*v)
	}
	return _u
}

// AddKumaInstanceID adds value to the "kuma_instance_id" field.
func (_u *MonitorUpdateOne) AddKumaInstanceID(v int) *MonitorUpdateOne {
	_u.mutation.AddKumaInstanceID(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MonitorUpdateOne) SetCreatedAt(v time.Time) *MonitorUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableCreatedAt(v *time.Time) *MonitorUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the MonitorMutation object of the builder.
func (_u *MonitorUpdateOne) Mutation() *MonitorMutation {
	return _u.mutation
}

// Where appends a list predicates to the MonitorUpdate builder.
func (_u *MonitorUpdateOne) Where(ps ...predicate.Monitor) *MonitorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MonitorUpdateOne) Select(field string, fields ...string) *MonitorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Monitor entity.
func (_u *MonitorUpdateOne) Save(ctx context.Context) (*Monitor, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorUpdateOne) SaveX(ctx context.Context) *Monitor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MonitorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *MonitorUpdateOne) sqlSave(ctx context.Context) (_node *Monitor, err error) {
	_spec := sqlgraph.NewUpdateSpec(monitor.Table, monitor.Columns, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Monitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitor.FieldID)
		for _, f := range fields {
			if !monitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(monitor.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(monitor.FieldServiceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.MonitorType(); ok {
		_spec.SetField(monitor.FieldMonitorType, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(monitor.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(monitor.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.DockerContainer(); ok {
		_spec.SetField(monitor.FieldDockerContainer, field.TypeString, value)
	}
	if _u.mutation.DockerContainerCleared() {
		_spec.ClearField(monitor.FieldDockerContainer, field.TypeString)
	}
	if value, ok := _u.mutation.KumaID(); ok {
		_spec.SetField(monitor.FieldKumaID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaID(); ok {
		_spec.AddField(monitor.FieldKumaID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaInstanceID(); ok {
		_spec.SetField(monitor.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaInstanceID(); ok {
		_spec.AddField(monitor.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(monitor.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Monitor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
