// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/npminstance"
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NPMInstanceUpdate is the builder for updating NPMInstance entities.
type NPMInstanceUpdate struct {
	config
	hooks    []Hook
	mutation *NPMInstanceMutation
}

// Where appends a list predicates to the NPMInstanceUpdate builder.
func (_u *NPMInstanceUpdate) Where(ps ...predicate.NPMInstance) *NPMInstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *NPMInstanceUpdate) SetName(v string) *NPMInstanceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillableName(v *string) *NPMInstanceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NPMInstanceUpdate) SetURL(v string) *NPMInstanceUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillableURL(v *string) *NPMInstanceUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *NPMInstanceUpdate) SetUsername(v string) *NPMInstanceUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillableUsername(v *string) *NPMInstanceUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *NPMInstanceUpdate) SetPassword(v string) *NPMInstanceUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillablePassword(v *string) *NPMInstanceUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NPMInstanceUpdate) SetEnabled(v bool) *NPMInstanceUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillableEnabled(v *bool) *NPMInstanceUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NPMInstanceUpdate) SetCreatedAt(v time.Time) *NPMInstanceUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NPMInstanceUpdate) SetNillableCreatedAt(v *time.Time) *NPMInstanceUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the NPMInstanceMutation object of the builder.
func (_u *NPMInstanceUpdate) Mutation() *NPMInstanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NPMInstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NPMInstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NPMInstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NPMInstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NPMInstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(npminstance.Table, npminstance.Columns, sqlgraph.NewFieldSpec(npminstance.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(npminstance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(npminstance.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(npminstance.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(npminstance.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(npminstance.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(npminstance.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{npminstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NPMInstanceUpdateOne is the builder for updating a single NPMInstance entity.
type NPMInstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NPMInstanceMutation
}

// SetName sets the "name" field.
func (_u *NPMInstanceUpdateOne) SetName(v string) *NPMInstanceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillableName(v *string) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *NPMInstanceUpdateOne) SetURL(v string) *NPMInstanceUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillableURL(v *string) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *NPMInstanceUpdateOne) SetUsername(v string) *NPMInstanceUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillableUsername(v *string) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *NPMInstanceUpdateOne) SetPassword(v string) *NPMInstanceUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillablePassword(v *string) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NPMInstanceUpdateOne) SetEnabled(v bool) *NPMInstanceUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillableEnabled(v *bool) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *NPMInstanceUpdateOne) SetCreatedAt(v time.Time) *NPMInstanceUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *NPMInstanceUpdateOne) SetNillableCreatedAt(v *time.Time) *NPMInstanceUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the NPMInstanceMutation object of the builder.
func (_u *NPMInstanceUpdateOne) Mutation() *NPMInstanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the NPMInstanceUpdate builder.
func (_u *NPMInstanceUpdateOne) Where(ps ...predicate.NPMInstance) *NPMInstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NPMInstanceUpdateOne) Select(field string, fields ...string) *NPMInstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NPMInstance entity.
func (_u *NPMInstanceUpdateOne) Save(ctx context.Context) (*NPMInstance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NPMInstanceUpdateOne) SaveX(ctx context.Context) *NPMInstance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NPMInstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NPMInstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *NPMInstanceUpdateOne) sqlSave(ctx context.Context) (_node *NPMInstance, err error) {
	_spec := sqlgraph.NewUpdateSpec(npminstance.Table, npminstance.Columns, sqlgraph.NewFieldSpec(npminstance.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NPMInstance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, npminstance.FieldID)
		for _, f := range fields {
			if !npminstance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != npminstance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(npminstance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(npminstance.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(npminstance.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(npminstance.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(npminstance.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(npminstance.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &NPMInstance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{npminstance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
