// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/npminstance"
	"synapse/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NPMInstanceDelete is the builder for deleting a NPMInstance entity.
type NPMInstanceDelete struct {
	config
	hooks    []Hook
	mutation *NPMInstanceMutation
}

// Where appends a list predicates to the NPMInstanceDelete builder.
func (_d *NPMInstanceDelete) Where(ps ...predicate.NPMInstance) *NPMInstanceDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *NPMInstanceDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NPMInstanceDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *NPMInstanceDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(npminstance.Table, sqlgraph.NewFieldSpec(npminstance.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// NPMInstanceDeleteOne is the builder for deleting a single NPMInstance entity.
type NPMInstanceDeleteOne struct {
	_d *NPMInstanceDelete
}

// Where appends a list predicates to the NPMInstanceDelete builder.
func (_d *NPMInstanceDeleteOne) Where(ps ...predicate.NPMInstance) *NPMInstanceDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *NPMInstanceDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{npminstance.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *NPMInstanceDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
