// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/npminstance"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NPMInstanceCreate is the builder for creating a NPMInstance entity.
type NPMInstanceCreate struct {
	config
	mutation *NPMInstanceMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *NPMInstanceCreate) SetName(v string) *NPMInstanceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetURL sets the "url" field.
func (_c *NPMInstanceCreate) SetURL(v string) *NPMInstanceCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *NPMInstanceCreate) SetUsername(v string) *NPMInstanceCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetPassword sets the "password" field.
func (_c *NPMInstanceCreate) SetPassword(v string) *NPMInstanceCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NPMInstanceCreate) SetEnabled(v bool) *NPMInstanceCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NPMInstanceCreate) SetNillableEnabled(v *bool) *NPMInstanceCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NPMInstanceCreate) SetCreatedAt(v time.Time) *NPMInstanceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// Mutation returns the NPMInstanceMutation object of the builder.
func (_c *NPMInstanceCreate) Mutation() *NPMInstanceMutation {
	return _c.mutation
}

// Save creates the NPMInstance in the database.
func (_c *NPMInstanceCreate) Save(ctx context.Context) (*NPMInstance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NPMInstanceCreate) SaveX(ctx context.Context) *NPMInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NPMInstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NPMInstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NPMInstanceCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := npminstance.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NPMInstanceCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NPMInstance.name"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "NPMInstance.url"`)}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "NPMInstance.username"`)}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "NPMInstance.password"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NPMInstance.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NPMInstance.created_at"`)}
	}
	return nil
}

func (_c *NPMInstanceCreate) sqlSave(ctx context.Context) (*NPMInstance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NPMInstanceCreate) createSpec() (*NPMInstance, *sqlgraph.CreateSpec) {
	var (
		_node = &NPMInstance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(npminstance.Table, sqlgraph.NewFieldSpec(npminstance.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(npminstance.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(npminstance.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(npminstance.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(npminstance.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(npminstance.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(npminstance.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// NPMInstanceCreateBulk is the builder for creating many NPMInstance entities in bulk.
type NPMInstanceCreateBulk struct {
	config
	err      error
	builders []*NPMInstanceCreate
}

// Save creates the NPMInstance entities in the database.
func (_c *NPMInstanceCreateBulk) Save(ctx context.Context) ([]*NPMInstance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NPMInstance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NPMInstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NPMInstanceCreateBulk) SaveX(ctx context.Context) []*NPMInstance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NPMInstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NPMInstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
