// Code generated by ent, DO NOT EDIT.

package ent

import (
	"synapse/ent/autheliaalert"
	"synapse/ent/autheliainstance"
	"synapse/ent/kumainstance"
	"synapse/ent/monitor"
	"synapse/ent/npminstance"
	"synapse/ent/schema"
	"synapse/ent/syncrun"
	"synapse/ent/tempaccess"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	autheliaalertFields := schema.AutheliaAlert{}.Fields()
	_ = autheliaalertFields
	// autheliaalertDescSeverity is the schema descriptor for severity field.
	autheliaalertDescSeverity := autheliaalertFields[2].Descriptor()
	// autheliaalert.DefaultSeverity holds the default value on creation for the severity field.
	autheliaalert.DefaultSeverity = autheliaalertDescSeverity.Default.(string)
	// autheliaalertDescStatus is the schema descriptor for status field.
	autheliaalertDescStatus := autheliaalertFields[3].Descriptor()
	// autheliaalert.DefaultStatus holds the default value on creation for the status field.
	autheliaalert.DefaultStatus = autheliaalertDescStatus.Default.(string)
	// autheliaalertDescAutheliaInstanceID is the schema descriptor for authelia_instance_id field.
	autheliaalertDescAutheliaInstanceID := autheliaalertFields[4].Descriptor()
	// autheliaalert.DefaultAutheliaInstanceID holds the default value on creation for the authelia_instance_id field.
	autheliaalert.DefaultAutheliaInstanceID = autheliaalertDescAutheliaInstanceID.Default.(int)
	autheliainstanceFields := schema.AutheliaInstance{}.Fields()
	_ = autheliainstanceFields
	// autheliainstanceDescDefaultPolicy is the schema descriptor for default_policy field.
	autheliainstanceDescDefaultPolicy := autheliainstanceFields[3].Descriptor()
	// autheliainstance.DefaultDefaultPolicy holds the default value on creation for the default_policy field.
	autheliainstance.DefaultDefaultPolicy = autheliainstanceDescDefaultPolicy.Default.(string)
	// autheliainstanceDescAutoSync is the schema descriptor for auto_sync field.
	autheliainstanceDescAutoSync := autheliainstanceFields[5].Descriptor()
	// autheliainstance.DefaultAutoSync holds the default value on creation for the auto_sync field.
	autheliainstance.DefaultAutoSync = autheliainstanceDescAutoSync.Default.(bool)
	// autheliainstanceDescEnabled is the schema descriptor for enabled field.
	autheliainstanceDescEnabled := autheliainstanceFields[7].Descriptor()
	// autheliainstance.DefaultEnabled holds the default value on creation for the enabled field.
	autheliainstance.DefaultEnabled = autheliainstanceDescEnabled.Default.(bool)
	kumainstanceFields := schema.KumaInstance{}.Fields()
	_ = kumainstanceFields
	// kumainstanceDescEnabled is the schema descriptor for enabled field.
	kumainstanceDescEnabled := kumainstanceFields[4].Descriptor()
	// kumainstance.DefaultEnabled holds the default value on creation for the enabled field.
	kumainstance.DefaultEnabled = kumainstanceDescEnabled.Default.(bool)
	monitorFields := schema.Monitor{}.Fields()
	_ = monitorFields
	// monitorDescURL is the schema descriptor for url field.
	monitorDescURL := monitorFields[3].Descriptor()
	// monitor.DefaultURL holds the default value on creation for the url field.
	monitor.DefaultURL = monitorDescURL.Default.(string)
	// monitorDescDockerContainer is the schema descriptor for docker_container field.
	monitorDescDockerContainer := monitorFields[4].Descriptor()
	// monitor.DefaultDockerContainer holds the default value on creation for the docker_container field.
	monitor.DefaultDockerContainer = monitorDescDockerContainer.Default.(string)
	// monitorDescKumaID is the schema descriptor for kuma_id field.
	monitorDescKumaID := monitorFields[5].Descriptor()
	// monitor.DefaultKumaID holds the default value on creation for the kuma_id field.
	monitor.DefaultKumaID = monitorDescKumaID.Default.(int)
	// monitorDescKumaInstanceID is the schema descriptor for kuma_instance_id field.
	monitorDescKumaInstanceID := monitorFields[6].Descriptor()
	// monitor.DefaultKumaInstanceID holds the default value on creation for the kuma_instance_id field.
	monitor.DefaultKumaInstanceID = monitorDescKumaInstanceID.Default.(int)
	npminstanceFields := schema.NPMInstance{}.Fields()
	_ = npminstanceFields
	// npminstanceDescEnabled is the schema descriptor for enabled field.
	npminstanceDescEnabled := npminstanceFields[4].Descriptor()
	// npminstance.DefaultEnabled holds the default value on creation for the enabled field.
	npminstance.DefaultEnabled = npminstanceDescEnabled.Default.(bool)
	syncrunFields := schema.SyncRun{}.Fields()
	_ = syncrunFields
	// syncrunDescSource is the schema descriptor for source field.
	syncrunDescSource := syncrunFields[0].Descriptor()
	// syncrun.DefaultSource holds the default value on creation for the source field.
	syncrun.DefaultSource = syncrunDescSource.Default.(string)
	// syncrunDescStatus is the schema descriptor for status field.
	syncrunDescStatus := syncrunFields[1].Descriptor()
	// syncrun.DefaultStatus holds the default value on creation for the status field.
	syncrun.DefaultStatus = syncrunDescStatus.Default.(string)
	// syncrunDescTotalServices is the schema descriptor for total_services field.
	syncrunDescTotalServices := syncrunFields[4].Descriptor()
	// syncrun.DefaultTotalServices holds the default value on creation for the total_services field.
	syncrun.DefaultTotalServices = syncrunDescTotalServices.Default.(int)
	// syncrunDescAdded is the schema descriptor for added field.
	syncrunDescAdded := syncrunFields[5].Descriptor()
	// syncrun.DefaultAdded holds the default value on creation for the added field.
	syncrun.DefaultAdded = syncrunDescAdded.Default.(int)
	// syncrunDescSkipped is the schema descriptor for skipped field.
	syncrunDescSkipped := syncrunFields[6].Descriptor()
	// syncrun.DefaultSkipped holds the default value on creation for the skipped field.
	syncrun.DefaultSkipped = syncrunDescSkipped.Default.(int)
	// syncrunDescFailed is the schema descriptor for failed field.
	syncrunDescFailed := syncrunFields[7].Descriptor()
	// syncrun.DefaultFailed holds the default value on creation for the failed field.
	syncrun.DefaultFailed = syncrunDescFailed.Default.(int)
	// syncrunDescErrorMessage is the schema descriptor for error_message field.
	syncrunDescErrorMessage := syncrunFields[8].Descriptor()
	// syncrun.DefaultErrorMessage holds the default value on creation for the error_message field.
	syncrun.DefaultErrorMessage = syncrunDescErrorMessage.Default.(string)
	tempaccessFields := schema.TempAccess{}.Fields()
	_ = tempaccessFields
	// tempaccessDescReason is the schema descriptor for reason field.
	tempaccessDescReason := tempaccessFields[1].Descriptor()
	// tempaccess.DefaultReason holds the default value on creation for the reason field.
	tempaccess.DefaultReason = tempaccessDescReason.Default.(string)
	// tempaccessDescAutheliaInstanceID is the schema descriptor for authelia_instance_id field.
	tempaccessDescAutheliaInstanceID := tempaccessFields[2].Descriptor()
	// tempaccess.DefaultAutheliaInstanceID holds the default value on creation for the authelia_instance_id field.
	tempaccess.DefaultAutheliaInstanceID = tempaccessDescAutheliaInstanceID.Default.(int)
	// tempaccessDescStatus is the schema descriptor for status field.
	tempaccessDescStatus := tempaccessFields[5].Descriptor()
	// tempaccess.DefaultStatus holds the default value on creation for the status field.
	tempaccess.DefaultStatus = tempaccessDescStatus.Default.(string)
}
