// Code generated by ent, DO NOT EDIT.

package ent

import (
	"synapse/ent/autheliaalert"
	"synapse/ent/autheliainstance"
	"synapse/ent/dockerevent"
	"synapse/ent/kumainstance"
	"synapse/ent/monitor"
	"synapse/ent/npminstance"
	"synapse/ent/schema"
	"synapse/ent/servicelink"
	"synapse/ent/syncrun"
	"synapse/ent/tempaccess"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	autheliaalertFields := schema.AutheliaAlert{}.Fields()
	_ = autheliaalertFields
	// autheliaalertDescSeverity is the schema descriptor for severity field.
	autheliaalertDescSeverity := autheliaalertFields[2].Descriptor()
	// autheliaalert.DefaultSeverity holds the default value on creation for the severity field.
	autheliaalert.DefaultSeverity = autheliaalertDescSeverity.Default.(string)
	// autheliaalertDescStatus is the schema descriptor for status field.
	autheliaalertDescStatus := autheliaalertFields[3].Descriptor()
	// autheliaalert.DefaultStatus holds the default value on creation for the status field.
	autheliaalert.DefaultStatus = autheliaalertDescStatus.Default.(string)
	// autheliaalertDescAutheliaInstanceID is the schema descriptor for authelia_instance_id field.
	autheliaalertDescAutheliaInstanceID := autheliaalertFields[4].Descriptor()
	// autheliaalert.DefaultAutheliaInstanceID holds the default value on creation for the authelia_instance_id field.
	autheliaalert.DefaultAutheliaInstanceID = autheliaalertDescAutheliaInstanceID.Default.(int)
	autheliainstanceFields := schema.AutheliaInstance{}.Fields()
	_ = autheliainstanceFields
	// autheliainstanceDescDefaultPolicy is the schema descriptor for default_policy field.
	autheliainstanceDescDefaultPolicy := autheliainstanceFields[3].Descriptor()
	// autheliainstance.DefaultDefaultPolicy holds the default value on creation for the default_policy field.
	autheliainstance.DefaultDefaultPolicy = autheliainstanceDescDefaultPolicy.Default.(string)
	// autheliainstanceDescAutoSync is the schema descriptor for auto_sync field.
	autheliainstanceDescAutoSync := autheliainstanceFields[5].Descriptor()
	// autheliainstance.DefaultAutoSync holds the default value on creation for the auto_sync field.
	autheliainstance.DefaultAutoSync = autheliainstanceDescAutoSync.Default.(bool)
	// autheliainstanceDescEnabled is the schema descriptor for enabled field.
	autheliainstanceDescEnabled := autheliainstanceFields[7].Descriptor()
	// autheliainstance.DefaultEnabled holds the default value on creation for the enabled field.
	autheliainstance.DefaultEnabled = autheliainstanceDescEnabled.Default.(bool)
	dockereventFields := schema.DockerEvent{}.Fields()
	_ = dockereventFields
	// dockereventDescEventType is the schema descriptor for event_type field.
	dockereventDescEventType := dockereventFields[0].Descriptor()
	// dockerevent.DefaultEventType holds the default value on creation for the event_type field.
	dockerevent.DefaultEventType = dockereventDescEventType.Default.(string)
	// dockereventDescAction is the schema descriptor for action field.
	dockereventDescAction := dockereventFields[1].Descriptor()
	// dockerevent.DefaultAction holds the default value on creation for the action field.
	dockerevent.DefaultAction = dockereventDescAction.Default.(string)
	// dockereventDescActorID is the schema descriptor for actor_id field.
	dockereventDescActorID := dockereventFields[2].Descriptor()
	// dockerevent.DefaultActorID holds the default value on creation for the actor_id field.
	dockerevent.DefaultActorID = dockereventDescActorID.Default.(string)
	// dockereventDescActorName is the schema descriptor for actor_name field.
	dockereventDescActorName := dockereventFields[3].Descriptor()
	// dockerevent.DefaultActorName holds the default value on creation for the actor_name field.
	dockerevent.DefaultActorName = dockereventDescActorName.Default.(string)
	// dockereventDescImage is the schema descriptor for image field.
	dockereventDescImage := dockereventFields[4].Descriptor()
	// dockerevent.DefaultImage holds the default value on creation for the image field.
	dockerevent.DefaultImage = dockereventDescImage.Default.(string)
	// dockereventDescStatus is the schema descriptor for status field.
	dockereventDescStatus := dockereventFields[5].Descriptor()
	// dockerevent.DefaultStatus holds the default value on creation for the status field.
	dockerevent.DefaultStatus = dockereventDescStatus.Default.(string)
	// dockereventDescImageOld is the schema descriptor for image_old field.
	dockereventDescImageOld := dockereventFields[6].Descriptor()
	// dockerevent.DefaultImageOld holds the default value on creation for the image_old field.
	dockerevent.DefaultImageOld = dockereventDescImageOld.Default.(string)
	// dockereventDescImageNew is the schema descriptor for image_new field.
	dockereventDescImageNew := dockereventFields[7].Descriptor()
	// dockerevent.DefaultImageNew holds the default value on creation for the image_new field.
	dockerevent.DefaultImageNew = dockereventDescImageNew.Default.(string)
	// dockereventDescPayload is the schema descriptor for payload field.
	dockereventDescPayload := dockereventFields[8].Descriptor()
	// dockerevent.DefaultPayload holds the default value on creation for the payload field.
	dockerevent.DefaultPayload = dockereventDescPayload.Default.(string)
	kumainstanceFields := schema.KumaInstance{}.Fields()
	_ = kumainstanceFields
	// kumainstanceDescEnabled is the schema descriptor for enabled field.
	kumainstanceDescEnabled := kumainstanceFields[4].Descriptor()
	// kumainstance.DefaultEnabled holds the default value on creation for the enabled field.
	kumainstance.DefaultEnabled = kumainstanceDescEnabled.Default.(bool)
	monitorFields := schema.Monitor{}.Fields()
	_ = monitorFields
	// monitorDescURL is the schema descriptor for url field.
	monitorDescURL := monitorFields[3].Descriptor()
	// monitor.DefaultURL holds the default value on creation for the url field.
	monitor.DefaultURL = monitorDescURL.Default.(string)
	// monitorDescDockerContainer is the schema descriptor for docker_container field.
	monitorDescDockerContainer := monitorFields[4].Descriptor()
	// monitor.DefaultDockerContainer holds the default value on creation for the docker_container field.
	monitor.DefaultDockerContainer = monitorDescDockerContainer.Default.(string)
	// monitorDescKumaID is the schema descriptor for kuma_id field.
	monitorDescKumaID := monitorFields[5].Descriptor()
	// monitor.DefaultKumaID holds the default value on creation for the kuma_id field.
	monitor.DefaultKumaID = monitorDescKumaID.Default.(int)
	// monitorDescKumaInstanceID is the schema descriptor for kuma_instance_id field.
	monitorDescKumaInstanceID := monitorFields[6].Descriptor()
	// monitor.DefaultKumaInstanceID holds the default value on creation for the kuma_instance_id field.
	monitor.DefaultKumaInstanceID = monitorDescKumaInstanceID.Default.(int)
	npminstanceFields := schema.NPMInstance{}.Fields()
	_ = npminstanceFields
	// npminstanceDescEnabled is the schema descriptor for enabled field.
	npminstanceDescEnabled := npminstanceFields[4].Descriptor()
	// npminstance.DefaultEnabled holds the default value on creation for the enabled field.
	npminstance.DefaultEnabled = npminstanceDescEnabled.Default.(bool)
	servicelinkFields := schema.ServiceLink{}.Fields()
	_ = servicelinkFields
	// servicelinkDescNpmInstanceID is the schema descriptor for npm_instance_id field.
	servicelinkDescNpmInstanceID := servicelinkFields[1].Descriptor()
	// servicelink.DefaultNpmInstanceID holds the default value on creation for the npm_instance_id field.
	servicelink.DefaultNpmInstanceID = servicelinkDescNpmInstanceID.Default.(int)
	// servicelinkDescNpmHostName is the schema descriptor for npm_host_name field.
	servicelinkDescNpmHostName := servicelinkFields[2].Descriptor()
	// servicelink.DefaultNpmHostName holds the default value on creation for the npm_host_name field.
	servicelink.DefaultNpmHostName = servicelinkDescNpmHostName.Default.(string)
	// servicelinkDescNpmDetails is the schema descriptor for npm_details field.
	servicelinkDescNpmDetails := servicelinkFields[3].Descriptor()
	// servicelink.DefaultNpmDetails holds the default value on creation for the npm_details field.
	servicelink.DefaultNpmDetails = servicelinkDescNpmDetails.Default.(string)
	// servicelinkDescKumaInstanceID is the schema descriptor for kuma_instance_id field.
	servicelinkDescKumaInstanceID := servicelinkFields[4].Descriptor()
	// servicelink.DefaultKumaInstanceID holds the default value on creation for the kuma_instance_id field.
	servicelink.DefaultKumaInstanceID = servicelinkDescKumaInstanceID.Default.(int)
	// servicelinkDescKumaMonitorID is the schema descriptor for kuma_monitor_id field.
	servicelinkDescKumaMonitorID := servicelinkFields[5].Descriptor()
	// servicelink.DefaultKumaMonitorID holds the default value on creation for the kuma_monitor_id field.
	servicelink.DefaultKumaMonitorID = servicelinkDescKumaMonitorID.Default.(int)
	// servicelinkDescKumaMonitorName is the schema descriptor for kuma_monitor_name field.
	servicelinkDescKumaMonitorName := servicelinkFields[6].Descriptor()
	// servicelink.DefaultKumaMonitorName holds the default value on creation for the kuma_monitor_name field.
	servicelink.DefaultKumaMonitorName = servicelinkDescKumaMonitorName.Default.(string)
	// servicelinkDescKumaDetails is the schema descriptor for kuma_details field.
	servicelinkDescKumaDetails := servicelinkFields[7].Descriptor()
	// servicelink.DefaultKumaDetails holds the default value on creation for the kuma_details field.
	servicelink.DefaultKumaDetails = servicelinkDescKumaDetails.Default.(string)
	syncrunFields := schema.SyncRun{}.Fields()
	_ = syncrunFields
	// syncrunDescSource is the schema descriptor for source field.
	syncrunDescSource := syncrunFields[0].Descriptor()
	// syncrun.DefaultSource holds the default value on creation for the source field.
	syncrun.DefaultSource = syncrunDescSource.Default.(string)
	// syncrunDescStatus is the schema descriptor for status field.
	syncrunDescStatus := syncrunFields[1].Descriptor()
	// syncrun.DefaultStatus holds the default value on creation for the status field.
	syncrun.DefaultStatus = syncrunDescStatus.Default.(string)
	// syncrunDescTotalServices is the schema descriptor for total_services field.
	syncrunDescTotalServices := syncrunFields[4].Descriptor()
	// syncrun.DefaultTotalServices holds the default value on creation for the total_services field.
	syncrun.DefaultTotalServices = syncrunDescTotalServices.Default.(int)
	// syncrunDescAdded is the schema descriptor for added field.
	syncrunDescAdded := syncrunFields[5].Descriptor()
	// syncrun.DefaultAdded holds the default value on creation for the added field.
	syncrun.DefaultAdded = syncrunDescAdded.Default.(int)
	// syncrunDescSkipped is the schema descriptor for skipped field.
	syncrunDescSkipped := syncrunFields[6].Descriptor()
	// syncrun.DefaultSkipped holds the default value on creation for the skipped field.
	syncrun.DefaultSkipped = syncrunDescSkipped.Default.(int)
	// syncrunDescFailed is the schema descriptor for failed field.
	syncrunDescFailed := syncrunFields[7].Descriptor()
	// syncrun.DefaultFailed holds the default value on creation for the failed field.
	syncrun.DefaultFailed = syncrunDescFailed.Default.(int)
	// syncrunDescErrorMessage is the schema descriptor for error_message field.
	syncrunDescErrorMessage := syncrunFields[8].Descriptor()
	// syncrun.DefaultErrorMessage holds the default value on creation for the error_message field.
	syncrun.DefaultErrorMessage = syncrunDescErrorMessage.Default.(string)
	// syncrunDescDryRun is the schema descriptor for dry_run field.
	syncrunDescDryRun := syncrunFields[9].Descriptor()
	// syncrun.DefaultDryRun holds the default value on creation for the dry_run field.
	syncrun.DefaultDryRun = syncrunDescDryRun.Default.(bool)
	tempaccessFields := schema.TempAccess{}.Fields()
	_ = tempaccessFields
	// tempaccessDescReason is the schema descriptor for reason field.
	tempaccessDescReason := tempaccessFields[1].Descriptor()
	// tempaccess.DefaultReason holds the default value on creation for the reason field.
	tempaccess.DefaultReason = tempaccessDescReason.Default.(string)
	// tempaccessDescAutheliaInstanceID is the schema descriptor for authelia_instance_id field.
	tempaccessDescAutheliaInstanceID := tempaccessFields[2].Descriptor()
	// tempaccess.DefaultAutheliaInstanceID holds the default value on creation for the authelia_instance_id field.
	tempaccess.DefaultAutheliaInstanceID = tempaccessDescAutheliaInstanceID.Default.(int)
	// tempaccessDescStatus is the schema descriptor for status field.
	tempaccessDescStatus := tempaccessFields[5].Descriptor()
	// tempaccess.DefaultStatus holds the default value on creation for the status field.
	tempaccess.DefaultStatus = tempaccessDescStatus.Default.(string)
}
