// Code generated by ent, DO NOT EDIT.

package ent

import (
	"synapse/ent/monitor"
	"synapse/ent/schema"
	"synapse/ent/syncrun"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	monitorFields := schema.Monitor{}.Fields()
	_ = monitorFields
	// monitorDescURL is the schema descriptor for url field.
	monitorDescURL := monitorFields[3].Descriptor()
	// monitor.DefaultURL holds the default value on creation for the url field.
	monitor.DefaultURL = monitorDescURL.Default.(string)
	// monitorDescDockerContainer is the schema descriptor for docker_container field.
	monitorDescDockerContainer := monitorFields[4].Descriptor()
	// monitor.DefaultDockerContainer holds the default value on creation for the docker_container field.
	monitor.DefaultDockerContainer = monitorDescDockerContainer.Default.(string)
	// monitorDescKumaID is the schema descriptor for kuma_id field.
	monitorDescKumaID := monitorFields[5].Descriptor()
	// monitor.DefaultKumaID holds the default value on creation for the kuma_id field.
	monitor.DefaultKumaID = monitorDescKumaID.Default.(int)
	syncrunFields := schema.SyncRun{}.Fields()
	_ = syncrunFields
	// syncrunDescSource is the schema descriptor for source field.
	syncrunDescSource := syncrunFields[0].Descriptor()
	// syncrun.DefaultSource holds the default value on creation for the source field.
	syncrun.DefaultSource = syncrunDescSource.Default.(string)
	// syncrunDescStatus is the schema descriptor for status field.
	syncrunDescStatus := syncrunFields[1].Descriptor()
	// syncrun.DefaultStatus holds the default value on creation for the status field.
	syncrun.DefaultStatus = syncrunDescStatus.Default.(string)
	// syncrunDescTotalServices is the schema descriptor for total_services field.
	syncrunDescTotalServices := syncrunFields[4].Descriptor()
	// syncrun.DefaultTotalServices holds the default value on creation for the total_services field.
	syncrun.DefaultTotalServices = syncrunDescTotalServices.Default.(int)
	// syncrunDescAdded is the schema descriptor for added field.
	syncrunDescAdded := syncrunFields[5].Descriptor()
	// syncrun.DefaultAdded holds the default value on creation for the added field.
	syncrun.DefaultAdded = syncrunDescAdded.Default.(int)
	// syncrunDescSkipped is the schema descriptor for skipped field.
	syncrunDescSkipped := syncrunFields[6].Descriptor()
	// syncrun.DefaultSkipped holds the default value on creation for the skipped field.
	syncrun.DefaultSkipped = syncrunDescSkipped.Default.(int)
	// syncrunDescFailed is the schema descriptor for failed field.
	syncrunDescFailed := syncrunFields[7].Descriptor()
	// syncrun.DefaultFailed holds the default value on creation for the failed field.
	syncrun.DefaultFailed = syncrunDescFailed.Default.(int)
	// syncrunDescErrorMessage is the schema descriptor for error_message field.
	syncrunDescErrorMessage := syncrunFields[8].Descriptor()
	// syncrun.DefaultErrorMessage holds the default value on creation for the error_message field.
	syncrun.DefaultErrorMessage = syncrunDescErrorMessage.Default.(string)
}
