// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/predicate"
	"synapse/ent/servicelink"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceLinkDelete is the builder for deleting a ServiceLink entity.
type ServiceLinkDelete struct {
	config
	hooks    []Hook
	mutation *ServiceLinkMutation
}

// Where appends a list predicates to the ServiceLinkDelete builder.
func (_d *ServiceLinkDelete) Where(ps ...predicate.ServiceLink) *ServiceLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ServiceLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ServiceLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(servicelink.Table, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ServiceLinkDeleteOne is the builder for deleting a single ServiceLink entity.
type ServiceLinkDeleteOne struct {
	_d *ServiceLinkDelete
}

// Where appends a list predicates to the ServiceLinkDelete builder.
func (_d *ServiceLinkDeleteOne) Where(ps ...predicate.ServiceLink) *ServiceLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ServiceLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{servicelink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ServiceLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
