// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/predicate"
	"synapse/ent/servicelink"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ServiceLinkUpdate is the builder for updating ServiceLink entities.
type ServiceLinkUpdate struct {
	config
	hooks    []Hook
	mutation *ServiceLinkMutation
}

// Where appends a list predicates to the ServiceLinkUpdate builder.
func (_u *ServiceLinkUpdate) Where(ps ...predicate.ServiceLink) *ServiceLinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetServiceName sets the "service_name" field.
func (_u *ServiceLinkUpdate) SetServiceName(v string) *ServiceLinkUpdate {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableServiceName(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// SetNpmInstanceID sets the "npm_instance_id" field.
func (_u *ServiceLinkUpdate) SetNpmInstanceID(v int) *ServiceLinkUpdate {
	_u.mutation.ResetNpmInstanceID()
	_u.mutation.SetNpmInstanceID(v)
	return _u
}

// SetNillableNpmInstanceID sets the "npm_instance_id" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableNpmInstanceID(v *int) *ServiceLinkUpdate {
	if v != nil {
		_u.SetNpmInstanceID(*v)
	}
	return _u
}

// AddNpmInstanceID adds value to the "npm_instance_id" field.
func (_u *ServiceLinkUpdate) AddNpmInstanceID(v int) *ServiceLinkUpdate {
	_u.mutation.AddNpmInstanceID(v)
	return _u
}

// SetNpmHostName sets the "npm_host_name" field.
func (_u *ServiceLinkUpdate) SetNpmHostName(v string) *ServiceLinkUpdate {
	_u.mutation.SetNpmHostName(v)
	return _u
}

// SetNillableNpmHostName sets the "npm_host_name" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableNpmHostName(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetNpmHostName(*v)
	}
	return _u
}

// ClearNpmHostName clears the value of the "npm_host_name" field.
func (_u *ServiceLinkUpdate) ClearNpmHostName() *ServiceLinkUpdate {
	_u.mutation.ClearNpmHostName()
	return _u
}

// SetNpmDetails sets the "npm_details" field.
func (_u *ServiceLinkUpdate) SetNpmDetails(v string) *ServiceLinkUpdate {
	_u.mutation.SetNpmDetails(v)
	return _u
}

// SetNillableNpmDetails sets the "npm_details" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableNpmDetails(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetNpmDetails(*v)
	}
	return _u
}

// ClearNpmDetails clears the value of the "npm_details" field.
func (_u *ServiceLinkUpdate) ClearNpmDetails() *ServiceLinkUpdate {
	_u.mutation.ClearNpmDetails()
	return _u
}

// SetKumaInstanceID sets the "kuma_instance_id" field.
func (_u *ServiceLinkUpdate) SetKumaInstanceID(v int) *ServiceLinkUpdate {
	_u.mutation.ResetKumaInstanceID()
	_u.mutation.SetKumaInstanceID(v)
	return _u
}

// SetNillableKumaInstanceID sets the "kuma_instance_id" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableKumaInstanceID(v *int) *ServiceLinkUpdate {
	if v != nil {
		_u.SetKumaInstanceID(*v)
	}
	return _u
}

// AddKumaInstanceID adds value to the "kuma_instance_id" field.
func (_u *ServiceLinkUpdate) AddKumaInstanceID(v int) *ServiceLinkUpdate {
	_u.mutation.AddKumaInstanceID(v)
	return _u
}

// SetKumaMonitorID sets the "kuma_monitor_id" field.
func (_u *ServiceLinkUpdate) SetKumaMonitorID(v int) *ServiceLinkUpdate {
	_u.mutation.ResetKumaMonitorID()
	_u.mutation.SetKumaMonitorID(v)
	return _u
}

// SetNillableKumaMonitorID sets the "kuma_monitor_id" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableKumaMonitorID(v *int) *ServiceLinkUpdate {
	if v != nil {
		_u.SetKumaMonitorID(*v)
	}
	return _u
}

// AddKumaMonitorID adds value to the "kuma_monitor_id" field.
func (_u *ServiceLinkUpdate) AddKumaMonitorID(v int) *ServiceLinkUpdate {
	_u.mutation.AddKumaMonitorID(v)
	return _u
}

// SetKumaMonitorName sets the "kuma_monitor_name" field.
func (_u *ServiceLinkUpdate) SetKumaMonitorName(v string) *ServiceLinkUpdate {
	_u.mutation.SetKumaMonitorName(v)
	return _u
}

// SetNillableKumaMonitorName sets the "kuma_monitor_name" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableKumaMonitorName(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetKumaMonitorName(*v)
	}
	return _u
}

// ClearKumaMonitorName clears the value of the "kuma_monitor_name" field.
func (_u *ServiceLinkUpdate) ClearKumaMonitorName() *ServiceLinkUpdate {
	_u.mutation.ClearKumaMonitorName()
	return _u
}

// SetKumaDetails sets the "kuma_details" field.
func (_u *ServiceLinkUpdate) SetKumaDetails(v string) *ServiceLinkUpdate {
	_u.mutation.SetKumaDetails(v)
	return _u
}

// SetNillableKumaDetails sets the "kuma_details" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableKumaDetails(v *string) *ServiceLinkUpdate {
	if v != nil {
		_u.SetKumaDetails(*v)
	}
	return _u
}

// ClearKumaDetails clears the value of the "kuma_details" field.
func (_u *ServiceLinkUpdate) ClearKumaDetails() *ServiceLinkUpdate {
	_u.mutation.ClearKumaDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServiceLinkUpdate) SetCreatedAt(v time.Time) *ServiceLinkUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableCreatedAt(v *time.Time) *ServiceLinkUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceLinkUpdate) SetUpdatedAt(v time.Time) *ServiceLinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ServiceLinkUpdate) SetNillableUpdatedAt(v *time.Time) *ServiceLinkUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ServiceLinkUpdate) ClearUpdatedAt() *ServiceLinkUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ServiceLinkMutation object of the builder.
func (_u *ServiceLinkUpdate) Mutation() *ServiceLinkMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ServiceLinkUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ServiceLinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceLinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServiceLinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(servicelink.Table, servicelink.Columns, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(servicelink.FieldServiceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NpmInstanceID(); ok {
		_spec.SetField(servicelink.FieldNpmInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNpmInstanceID(); ok {
		_spec.AddField(servicelink.FieldNpmInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NpmHostName(); ok {
		_spec.SetField(servicelink.FieldNpmHostName, field.TypeString, value)
	}
	if _u.mutation.NpmHostNameCleared() {
		_spec.ClearField(servicelink.FieldNpmHostName, field.TypeString)
	}
	if value, ok := _u.mutation.NpmDetails(); ok {
		_spec.SetField(servicelink.FieldNpmDetails, field.TypeString, value)
	}
	if _u.mutation.NpmDetailsCleared() {
		_spec.ClearField(servicelink.FieldNpmDetails, field.TypeString)
	}
	if value, ok := _u.mutation.KumaInstanceID(); ok {
		_spec.SetField(servicelink.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaInstanceID(); ok {
		_spec.AddField(servicelink.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaMonitorID(); ok {
		_spec.SetField(servicelink.FieldKumaMonitorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaMonitorID(); ok {
		_spec.AddField(servicelink.FieldKumaMonitorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaMonitorName(); ok {
		_spec.SetField(servicelink.FieldKumaMonitorName, field.TypeString, value)
	}
	if _u.mutation.KumaMonitorNameCleared() {
		_spec.ClearField(servicelink.FieldKumaMonitorName, field.TypeString)
	}
	if value, ok := _u.mutation.KumaDetails(); ok {
		_spec.SetField(servicelink.FieldKumaDetails, field.TypeString, value)
	}
	if _u.mutation.KumaDetailsCleared() {
		_spec.ClearField(servicelink.FieldKumaDetails, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(servicelink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicelink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(servicelink.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ServiceLinkUpdateOne is the builder for updating a single ServiceLink entity.
type ServiceLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ServiceLinkMutation
}

// SetServiceName sets the "service_name" field.
func (_u *ServiceLinkUpdateOne) SetServiceName(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetServiceName(v)
	return _u
}

// SetNillableServiceName sets the "service_name" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableServiceName(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetServiceName(*v)
	}
	return _u
}

// SetNpmInstanceID sets the "npm_instance_id" field.
func (_u *ServiceLinkUpdateOne) SetNpmInstanceID(v int) *ServiceLinkUpdateOne {
	_u.mutation.ResetNpmInstanceID()
	_u.mutation.SetNpmInstanceID(v)
	return _u
}

// SetNillableNpmInstanceID sets the "npm_instance_id" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableNpmInstanceID(v *int) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetNpmInstanceID(*v)
	}
	return _u
}

// AddNpmInstanceID adds value to the "npm_instance_id" field.
func (_u *ServiceLinkUpdateOne) AddNpmInstanceID(v int) *ServiceLinkUpdateOne {
	_u.mutation.AddNpmInstanceID(v)
	return _u
}

// SetNpmHostName sets the "npm_host_name" field.
func (_u *ServiceLinkUpdateOne) SetNpmHostName(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetNpmHostName(v)
	return _u
}

// SetNillableNpmHostName sets the "npm_host_name" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableNpmHostName(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetNpmHostName(*v)
	}
	return _u
}

// ClearNpmHostName clears the value of the "npm_host_name" field.
func (_u *ServiceLinkUpdateOne) ClearNpmHostName() *ServiceLinkUpdateOne {
	_u.mutation.ClearNpmHostName()
	return _u
}

// SetNpmDetails sets the "npm_details" field.
func (_u *ServiceLinkUpdateOne) SetNpmDetails(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetNpmDetails(v)
	return _u
}

// SetNillableNpmDetails sets the "npm_details" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableNpmDetails(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetNpmDetails(*v)
	}
	return _u
}

// ClearNpmDetails clears the value of the "npm_details" field.
func (_u *ServiceLinkUpdateOne) ClearNpmDetails() *ServiceLinkUpdateOne {
	_u.mutation.ClearNpmDetails()
	return _u
}

// SetKumaInstanceID sets the "kuma_instance_id" field.
func (_u *ServiceLinkUpdateOne) SetKumaInstanceID(v int) *ServiceLinkUpdateOne {
	_u.mutation.ResetKumaInstanceID()
	_u.mutation.SetKumaInstanceID(v)
	return _u
}

// SetNillableKumaInstanceID sets the "kuma_instance_id" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableKumaInstanceID(v *int) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetKumaInstanceID(*v)
	}
	return _u
}

// AddKumaInstanceID adds value to the "kuma_instance_id" field.
func (_u *ServiceLinkUpdateOne) AddKumaInstanceID(v int) *ServiceLinkUpdateOne {
	_u.mutation.AddKumaInstanceID(v)
	return _u
}

// SetKumaMonitorID sets the "kuma_monitor_id" field.
func (_u *ServiceLinkUpdateOne) SetKumaMonitorID(v int) *ServiceLinkUpdateOne {
	_u.mutation.ResetKumaMonitorID()
	_u.mutation.SetKumaMonitorID(v)
	return _u
}

// SetNillableKumaMonitorID sets the "kuma_monitor_id" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableKumaMonitorID(v *int) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetKumaMonitorID(*v)
	}
	return _u
}

// AddKumaMonitorID adds value to the "kuma_monitor_id" field.
func (_u *ServiceLinkUpdateOne) AddKumaMonitorID(v int) *ServiceLinkUpdateOne {
	_u.mutation.AddKumaMonitorID(v)
	return _u
}

// SetKumaMonitorName sets the "kuma_monitor_name" field.
func (_u *ServiceLinkUpdateOne) SetKumaMonitorName(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetKumaMonitorName(v)
	return _u
}

// SetNillableKumaMonitorName sets the "kuma_monitor_name" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableKumaMonitorName(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetKumaMonitorName(*v)
	}
	return _u
}

// ClearKumaMonitorName clears the value of the "kuma_monitor_name" field.
func (_u *ServiceLinkUpdateOne) ClearKumaMonitorName() *ServiceLinkUpdateOne {
	_u.mutation.ClearKumaMonitorName()
	return _u
}

// SetKumaDetails sets the "kuma_details" field.
func (_u *ServiceLinkUpdateOne) SetKumaDetails(v string) *ServiceLinkUpdateOne {
	_u.mutation.SetKumaDetails(v)
	return _u
}

// SetNillableKumaDetails sets the "kuma_details" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableKumaDetails(v *string) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetKumaDetails(*v)
	}
	return _u
}

// ClearKumaDetails clears the value of the "kuma_details" field.
func (_u *ServiceLinkUpdateOne) ClearKumaDetails() *ServiceLinkUpdateOne {
	_u.mutation.ClearKumaDetails()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ServiceLinkUpdateOne) SetCreatedAt(v time.Time) *ServiceLinkUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableCreatedAt(v *time.Time) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ServiceLinkUpdateOne) SetUpdatedAt(v time.Time) *ServiceLinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *ServiceLinkUpdateOne) SetNillableUpdatedAt(v *time.Time) *ServiceLinkUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ServiceLinkUpdateOne) ClearUpdatedAt() *ServiceLinkUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the ServiceLinkMutation object of the builder.
func (_u *ServiceLinkUpdateOne) Mutation() *ServiceLinkMutation {
	return _u.mutation
}

// Where appends a list predicates to the ServiceLinkUpdate builder.
func (_u *ServiceLinkUpdateOne) Where(ps ...predicate.ServiceLink) *ServiceLinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ServiceLinkUpdateOne) Select(field string, fields ...string) *ServiceLinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ServiceLink entity.
func (_u *ServiceLinkUpdateOne) Save(ctx context.Context) (*ServiceLink, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ServiceLinkUpdateOne) SaveX(ctx context.Context) *ServiceLink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ServiceLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ServiceLinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ServiceLinkUpdateOne) sqlSave(ctx context.Context) (_node *ServiceLink, err error) {
	_spec := sqlgraph.NewUpdateSpec(servicelink.Table, servicelink.Columns, sqlgraph.NewFieldSpec(servicelink.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ServiceLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, servicelink.FieldID)
		for _, f := range fields {
			if !servicelink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != servicelink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ServiceName(); ok {
		_spec.SetField(servicelink.FieldServiceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.NpmInstanceID(); ok {
		_spec.SetField(servicelink.FieldNpmInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedNpmInstanceID(); ok {
		_spec.AddField(servicelink.FieldNpmInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.NpmHostName(); ok {
		_spec.SetField(servicelink.FieldNpmHostName, field.TypeString, value)
	}
	if _u.mutation.NpmHostNameCleared() {
		_spec.ClearField(servicelink.FieldNpmHostName, field.TypeString)
	}
	if value, ok := _u.mutation.NpmDetails(); ok {
		_spec.SetField(servicelink.FieldNpmDetails, field.TypeString, value)
	}
	if _u.mutation.NpmDetailsCleared() {
		_spec.ClearField(servicelink.FieldNpmDetails, field.TypeString)
	}
	if value, ok := _u.mutation.KumaInstanceID(); ok {
		_spec.SetField(servicelink.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaInstanceID(); ok {
		_spec.AddField(servicelink.FieldKumaInstanceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaMonitorID(); ok {
		_spec.SetField(servicelink.FieldKumaMonitorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKumaMonitorID(); ok {
		_spec.AddField(servicelink.FieldKumaMonitorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.KumaMonitorName(); ok {
		_spec.SetField(servicelink.FieldKumaMonitorName, field.TypeString, value)
	}
	if _u.mutation.KumaMonitorNameCleared() {
		_spec.ClearField(servicelink.FieldKumaMonitorName, field.TypeString)
	}
	if value, ok := _u.mutation.KumaDetails(); ok {
		_spec.SetField(servicelink.FieldKumaDetails, field.TypeString, value)
	}
	if _u.mutation.KumaDetailsCleared() {
		_spec.ClearField(servicelink.FieldKumaDetails, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(servicelink.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(servicelink.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(servicelink.FieldUpdatedAt, field.TypeTime)
	}
	_node = &ServiceLink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{servicelink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
