// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/servicelink"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ServiceLink is the model entity for the ServiceLink schema.
type ServiceLink struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ServiceName holds the value of the "service_name" field.
	ServiceName string `json:"service_name,omitempty"`
	// NpmInstanceID holds the value of the "npm_instance_id" field.
	NpmInstanceID int `json:"npm_instance_id,omitempty"`
	// NpmHostName holds the value of the "npm_host_name" field.
	NpmHostName string `json:"npm_host_name,omitempty"`
	// NpmDetails holds the value of the "npm_details" field.
	NpmDetails string `json:"npm_details,omitempty"`
	// KumaInstanceID holds the value of the "kuma_instance_id" field.
	KumaInstanceID int `json:"kuma_instance_id,omitempty"`
	// KumaMonitorID holds the value of the "kuma_monitor_id" field.
	KumaMonitorID int `json:"kuma_monitor_id,omitempty"`
	// KumaMonitorName holds the value of the "kuma_monitor_name" field.
	KumaMonitorName string `json:"kuma_monitor_name,omitempty"`
	// KumaDetails holds the value of the "kuma_details" field.
	KumaDetails string `json:"kuma_details,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ServiceLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case servicelink.FieldID, servicelink.FieldNpmInstanceID, servicelink.FieldKumaInstanceID, servicelink.FieldKumaMonitorID:
			values[i] = new(sql.NullInt64)
		case servicelink.FieldServiceName, servicelink.FieldNpmHostName, servicelink.FieldNpmDetails, servicelink.FieldKumaMonitorName, servicelink.FieldKumaDetails:
			values[i] = new(sql.NullString)
		case servicelink.FieldCreatedAt, servicelink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ServiceLink fields.
func (_m *ServiceLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case servicelink.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case servicelink.FieldServiceName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field service_name", values[i])
			} else if value.Valid {
				_m.ServiceName = value.String
			}
		case servicelink.FieldNpmInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field npm_instance_id", values[i])
			} else if value.Valid {
				_m.NpmInstanceID = int(value.Int64)
			}
		case servicelink.FieldNpmHostName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field npm_host_name", values[i])
			} else if value.Valid {
				_m.NpmHostName = value.String
			}
		case servicelink.FieldNpmDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field npm_details", values[i])
			} else if value.Valid {
				_m.NpmDetails = value.String
			}
		case servicelink.FieldKumaInstanceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field kuma_instance_id", values[i])
			} else if value.Valid {
				_m.KumaInstanceID = int(value.Int64)
			}
		case servicelink.FieldKumaMonitorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field kuma_monitor_id", values[i])
			} else if value.Valid {
				_m.KumaMonitorID = int(value.Int64)
			}
		case servicelink.FieldKumaMonitorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kuma_monitor_name", values[i])
			} else if value.Valid {
				_m.KumaMonitorName = value.String
			}
		case servicelink.FieldKumaDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kuma_details", values[i])
			} else if value.Valid {
				_m.KumaDetails = value.String
			}
		case servicelink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case servicelink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ServiceLink.
// This includes values selected through modifiers, order, etc.
func (_m *ServiceLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ServiceLink.
// Note that you need to call ServiceLink.Unwrap() before calling this method if this ServiceLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ServiceLink) Update() *ServiceLinkUpdateOne {
	return NewServiceLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ServiceLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ServiceLink) Unwrap() *ServiceLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ServiceLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ServiceLink) String() string {
	var builder strings.Builder
	builder.WriteString("ServiceLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("service_name=")
	builder.WriteString(_m.ServiceName)
	builder.WriteString(", ")
	builder.WriteString("npm_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.NpmInstanceID))
	builder.WriteString(", ")
	builder.WriteString("npm_host_name=")
	builder.WriteString(_m.NpmHostName)
	builder.WriteString(", ")
	builder.WriteString("npm_details=")
	builder.WriteString(_m.NpmDetails)
	builder.WriteString(", ")
	builder.WriteString("kuma_instance_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KumaInstanceID))
	builder.WriteString(", ")
	builder.WriteString("kuma_monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.KumaMonitorID))
	builder.WriteString(", ")
	builder.WriteString("kuma_monitor_name=")
	builder.WriteString(_m.KumaMonitorName)
	builder.WriteString(", ")
	builder.WriteString("kuma_details=")
	builder.WriteString(_m.KumaDetails)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ServiceLinks is a parsable slice of ServiceLink.
type ServiceLinks []*ServiceLink
