// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"synapse/ent/syncrun"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SyncRun is the model entity for the SyncRun schema.
type SyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// TotalServices holds the value of the "total_services" field.
	TotalServices int `json:"total_services,omitempty"`
	// Added holds the value of the "added" field.
	Added int `json:"added,omitempty"`
	// Skipped holds the value of the "skipped" field.
	Skipped int `json:"skipped,omitempty"`
	// Failed holds the value of the "failed" field.
	Failed int `json:"failed,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage string `json:"error_message,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case syncrun.FieldID, syncrun.FieldTotalServices, syncrun.FieldAdded, syncrun.FieldSkipped, syncrun.FieldFailed:
			values[i] = new(sql.NullInt64)
		case syncrun.FieldSource, syncrun.FieldStatus, syncrun.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case syncrun.FieldStartedAt, syncrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SyncRun fields.
func (_m *SyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case syncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case syncrun.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case syncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case syncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case syncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case syncrun.FieldTotalServices:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_services", values[i])
			} else if value.Valid {
				_m.TotalServices = int(value.Int64)
			}
		case syncrun.FieldAdded:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field added", values[i])
			} else if value.Valid {
				_m.Added = int(value.Int64)
			}
		case syncrun.FieldSkipped:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field skipped", values[i])
			} else if value.Valid {
				_m.Skipped = int(value.Int64)
			}
		case syncrun.FieldFailed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed", values[i])
			} else if value.Valid {
				_m.Failed = int(value.Int64)
			}
		case syncrun.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *SyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SyncRun.
// Note that you need to call SyncRun.Unwrap() before calling this method if this SyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SyncRun) Update() *SyncRunUpdateOne {
	return NewSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SyncRun) Unwrap() *SyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("SyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("total_services=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalServices))
	builder.WriteString(", ")
	builder.WriteString("added=")
	builder.WriteString(fmt.Sprintf("%v", _m.Added))
	builder.WriteString(", ")
	builder.WriteString("skipped=")
	builder.WriteString(fmt.Sprintf("%v", _m.Skipped))
	builder.WriteString(", ")
	builder.WriteString("failed=")
	builder.WriteString(fmt.Sprintf("%v", _m.Failed))
	builder.WriteString(", ")
	builder.WriteString("error_message=")
	builder.WriteString(_m.ErrorMessage)
	builder.WriteByte(')')
	return builder.String()
}

// SyncRuns is a parsable slice of SyncRun.
type SyncRuns []*SyncRun
