// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/predicate"
	"synapse/ent/syncrun"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncRunUpdate is the builder for updating SyncRun entities.
type SyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *SyncRunMutation
}

// Where appends a list predicates to the SyncRunUpdate builder.
func (_u *SyncRunUpdate) Where(ps ...predicate.SyncRun) *SyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSource sets the "source" field.
func (_u *SyncRunUpdate) SetSource(v string) *SyncRunUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableSource(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunUpdate) SetStatus(v string) *SyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableStatus(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunUpdate) SetStartedAt(v time.Time) *SyncRunUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableStartedAt(v *time.Time) *SyncRunUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunUpdate) SetFinishedAt(v time.Time) *SyncRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableFinishedAt(v *time.Time) *SyncRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncRunUpdate) ClearFinishedAt() *SyncRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTotalServices sets the "total_services" field.
func (_u *SyncRunUpdate) SetTotalServices(v int) *SyncRunUpdate {
	_u.mutation.ResetTotalServices()
	_u.mutation.SetTotalServices(v)
	return _u
}

// SetNillableTotalServices sets the "total_services" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableTotalServices(v *int) *SyncRunUpdate {
	if v != nil {
		_u.SetTotalServices(*v)
	}
	return _u
}

// AddTotalServices adds value to the "total_services" field.
func (_u *SyncRunUpdate) AddTotalServices(v int) *SyncRunUpdate {
	_u.mutation.AddTotalServices(v)
	return _u
}

// SetAdded sets the "added" field.
func (_u *SyncRunUpdate) SetAdded(v int) *SyncRunUpdate {
	_u.mutation.ResetAdded()
	_u.mutation.SetAdded(v)
	return _u
}

// SetNillableAdded sets the "added" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableAdded(v *int) *SyncRunUpdate {
	if v != nil {
		_u.SetAdded(*v)
	}
	return _u
}

// AddAdded adds value to the "added" field.
func (_u *SyncRunUpdate) AddAdded(v int) *SyncRunUpdate {
	_u.mutation.AddAdded(v)
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *SyncRunUpdate) SetUpdated(v int) *SyncRunUpdate {
	_u.mutation.ResetUpdated()
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableUpdated(v *int) *SyncRunUpdate {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// AddUpdated adds value to the "updated" field.
func (_u *SyncRunUpdate) AddUpdated(v int) *SyncRunUpdate {
	_u.mutation.AddUpdated(v)
	return _u
}

// SetSkipped sets the "skipped" field.
func (_u *SyncRunUpdate) SetSkipped(v int) *SyncRunUpdate {
	_u.mutation.ResetSkipped()
	_u.mutation.SetSkipped(v)
	return _u
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableSkipped(v *int) *SyncRunUpdate {
	if v != nil {
		_u.SetSkipped(*v)
	}
	return _u
}

// AddSkipped adds value to the "skipped" field.
func (_u *SyncRunUpdate) AddSkipped(v int) *SyncRunUpdate {
	_u.mutation.AddSkipped(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *SyncRunUpdate) SetFailed(v int) *SyncRunUpdate {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableFailed(v *int) *SyncRunUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *SyncRunUpdate) AddFailed(v int) *SyncRunUpdate {
	_u.mutation.AddFailed(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SyncRunUpdate) SetErrorMessage(v string) *SyncRunUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableErrorMessage(v *string) *SyncRunUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SyncRunUpdate) ClearErrorMessage() *SyncRunUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDryRun sets the "dry_run" field.
func (_u *SyncRunUpdate) SetDryRun(v bool) *SyncRunUpdate {
	_u.mutation.SetDryRun(v)
	return _u
}

// SetNillableDryRun sets the "dry_run" field if the given value is not nil.
func (_u *SyncRunUpdate) SetNillableDryRun(v *bool) *SyncRunUpdate {
	if v != nil {
		_u.SetDryRun(*v)
	}
	return _u
}

// ClearDryRun clears the value of the "dry_run" field.
func (_u *SyncRunUpdate) ClearDryRun() *SyncRunUpdate {
	_u.mutation.ClearDryRun()
	return _u
}

// Mutation returns the SyncRunMutation object of the builder.
func (_u *SyncRunUpdate) Mutation() *SyncRunMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SyncRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncrun.Table, syncrun.Columns, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(syncrun.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TotalServices(); ok {
		_spec.SetField(syncrun.FieldTotalServices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalServices(); ok {
		_spec.AddField(syncrun.FieldTotalServices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Added(); ok {
		_spec.SetField(syncrun.FieldAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdded(); ok {
		_spec.AddField(syncrun.FieldAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(syncrun.FieldUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdated(); ok {
		_spec.AddField(syncrun.FieldUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Skipped(); ok {
		_spec.SetField(syncrun.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkipped(); ok {
		_spec.AddField(syncrun.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(syncrun.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(syncrun.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(syncrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(syncrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DryRun(); ok {
		_spec.SetField(syncrun.FieldDryRun, field.TypeBool, value)
	}
	if _u.mutation.DryRunCleared() {
		_spec.ClearField(syncrun.FieldDryRun, field.TypeBool)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SyncRunUpdateOne is the builder for updating a single SyncRun entity.
type SyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SyncRunMutation
}

// SetSource sets the "source" field.
func (_u *SyncRunUpdateOne) SetSource(v string) *SyncRunUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableSource(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SyncRunUpdateOne) SetStatus(v string) *SyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableStatus(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *SyncRunUpdateOne) SetStartedAt(v time.Time) *SyncRunUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableStartedAt(v *time.Time) *SyncRunUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *SyncRunUpdateOne) SetFinishedAt(v time.Time) *SyncRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableFinishedAt(v *time.Time) *SyncRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *SyncRunUpdateOne) ClearFinishedAt() *SyncRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTotalServices sets the "total_services" field.
func (_u *SyncRunUpdateOne) SetTotalServices(v int) *SyncRunUpdateOne {
	_u.mutation.ResetTotalServices()
	_u.mutation.SetTotalServices(v)
	return _u
}

// SetNillableTotalServices sets the "total_services" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableTotalServices(v *int) *SyncRunUpdateOne {
	if v != nil {
		_u.SetTotalServices(*v)
	}
	return _u
}

// AddTotalServices adds value to the "total_services" field.
func (_u *SyncRunUpdateOne) AddTotalServices(v int) *SyncRunUpdateOne {
	_u.mutation.AddTotalServices(v)
	return _u
}

// SetAdded sets the "added" field.
func (_u *SyncRunUpdateOne) SetAdded(v int) *SyncRunUpdateOne {
	_u.mutation.ResetAdded()
	_u.mutation.SetAdded(v)
	return _u
}

// SetNillableAdded sets the "added" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableAdded(v *int) *SyncRunUpdateOne {
	if v != nil {
		_u.SetAdded(*v)
	}
	return _u
}

// AddAdded adds value to the "added" field.
func (_u *SyncRunUpdateOne) AddAdded(v int) *SyncRunUpdateOne {
	_u.mutation.AddAdded(v)
	return _u
}

// SetUpdated sets the "updated" field.
func (_u *SyncRunUpdateOne) SetUpdated(v int) *SyncRunUpdateOne {
	_u.mutation.ResetUpdated()
	_u.mutation.SetUpdated(v)
	return _u
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableUpdated(v *int) *SyncRunUpdateOne {
	if v != nil {
		_u.SetUpdated(*v)
	}
	return _u
}

// AddUpdated adds value to the "updated" field.
func (_u *SyncRunUpdateOne) AddUpdated(v int) *SyncRunUpdateOne {
	_u.mutation.AddUpdated(v)
	return _u
}

// SetSkipped sets the "skipped" field.
func (_u *SyncRunUpdateOne) SetSkipped(v int) *SyncRunUpdateOne {
	_u.mutation.ResetSkipped()
	_u.mutation.SetSkipped(v)
	return _u
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableSkipped(v *int) *SyncRunUpdateOne {
	if v != nil {
		_u.SetSkipped(*v)
	}
	return _u
}

// AddSkipped adds value to the "skipped" field.
func (_u *SyncRunUpdateOne) AddSkipped(v int) *SyncRunUpdateOne {
	_u.mutation.AddSkipped(v)
	return _u
}

// SetFailed sets the "failed" field.
func (_u *SyncRunUpdateOne) SetFailed(v int) *SyncRunUpdateOne {
	_u.mutation.ResetFailed()
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableFailed(v *int) *SyncRunUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// AddFailed adds value to the "failed" field.
func (_u *SyncRunUpdateOne) AddFailed(v int) *SyncRunUpdateOne {
	_u.mutation.AddFailed(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *SyncRunUpdateOne) SetErrorMessage(v string) *SyncRunUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableErrorMessage(v *string) *SyncRunUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *SyncRunUpdateOne) ClearErrorMessage() *SyncRunUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetDryRun sets the "dry_run" field.
func (_u *SyncRunUpdateOne) SetDryRun(v bool) *SyncRunUpdateOne {
	_u.mutation.SetDryRun(v)
	return _u
}

// SetNillableDryRun sets the "dry_run" field if the given value is not nil.
func (_u *SyncRunUpdateOne) SetNillableDryRun(v *bool) *SyncRunUpdateOne {
	if v != nil {
		_u.SetDryRun(*v)
	}
	return _u
}

// ClearDryRun clears the value of the "dry_run" field.
func (_u *SyncRunUpdateOne) ClearDryRun() *SyncRunUpdateOne {
	_u.mutation.ClearDryRun()
	return _u
}

// Mutation returns the SyncRunMutation object of the builder.
func (_u *SyncRunUpdateOne) Mutation() *SyncRunMutation {
	return _u.mutation
}

// Where appends a list predicates to the SyncRunUpdate builder.
func (_u *SyncRunUpdateOne) Where(ps ...predicate.SyncRun) *SyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SyncRunUpdateOne) Select(field string, fields ...string) *SyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SyncRun entity.
func (_u *SyncRunUpdateOne) Save(ctx context.Context) (*SyncRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SyncRunUpdateOne) SaveX(ctx context.Context) *SyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SyncRunUpdateOne) sqlSave(ctx context.Context) (_node *SyncRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(syncrun.Table, syncrun.Columns, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncrun.FieldID)
		for _, f := range fields {
			if !syncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != syncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(syncrun.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(syncrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(syncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TotalServices(); ok {
		_spec.SetField(syncrun.FieldTotalServices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalServices(); ok {
		_spec.AddField(syncrun.FieldTotalServices, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Added(); ok {
		_spec.SetField(syncrun.FieldAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdded(); ok {
		_spec.AddField(syncrun.FieldAdded, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Updated(); ok {
		_spec.SetField(syncrun.FieldUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUpdated(); ok {
		_spec.AddField(syncrun.FieldUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Skipped(); ok {
		_spec.SetField(syncrun.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSkipped(); ok {
		_spec.AddField(syncrun.FieldSkipped, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(syncrun.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailed(); ok {
		_spec.AddField(syncrun.FieldFailed, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(syncrun.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(syncrun.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.DryRun(); ok {
		_spec.SetField(syncrun.FieldDryRun, field.TypeBool, value)
	}
	if _u.mutation.DryRunCleared() {
		_spec.ClearField(syncrun.FieldDryRun, field.TypeBool)
	}
	_node = &SyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{syncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
