// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/syncrun"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SyncRunCreate is the builder for creating a SyncRun entity.
type SyncRunCreate struct {
	config
	mutation *SyncRunMutation
	hooks    []Hook
}

// SetSource sets the "source" field.
func (_c *SyncRunCreate) SetSource(v string) *SyncRunCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableSource(v *string) *SyncRunCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SyncRunCreate) SetStatus(v string) *SyncRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableStatus(v *string) *SyncRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SyncRunCreate) SetStartedAt(v time.Time) *SyncRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *SyncRunCreate) SetFinishedAt(v time.Time) *SyncRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableFinishedAt(v *time.Time) *SyncRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetTotalServices sets the "total_services" field.
func (_c *SyncRunCreate) SetTotalServices(v int) *SyncRunCreate {
	_c.mutation.SetTotalServices(v)
	return _c
}

// SetNillableTotalServices sets the "total_services" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableTotalServices(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetTotalServices(*v)
	}
	return _c
}

// SetAdded sets the "added" field.
func (_c *SyncRunCreate) SetAdded(v int) *SyncRunCreate {
	_c.mutation.SetAdded(v)
	return _c
}

// SetNillableAdded sets the "added" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableAdded(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetAdded(*v)
	}
	return _c
}

// SetUpdated sets the "updated" field.
func (_c *SyncRunCreate) SetUpdated(v int) *SyncRunCreate {
	_c.mutation.SetUpdated(v)
	return _c
}

// SetNillableUpdated sets the "updated" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableUpdated(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetUpdated(*v)
	}
	return _c
}

// SetSkipped sets the "skipped" field.
func (_c *SyncRunCreate) SetSkipped(v int) *SyncRunCreate {
	_c.mutation.SetSkipped(v)
	return _c
}

// SetNillableSkipped sets the "skipped" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableSkipped(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetSkipped(*v)
	}
	return _c
}

// SetFailed sets the "failed" field.
func (_c *SyncRunCreate) SetFailed(v int) *SyncRunCreate {
	_c.mutation.SetFailed(v)
	return _c
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableFailed(v *int) *SyncRunCreate {
	if v != nil {
		_c.SetFailed(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *SyncRunCreate) SetErrorMessage(v string) *SyncRunCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableErrorMessage(v *string) *SyncRunCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetDryRun sets the "dry_run" field.
func (_c *SyncRunCreate) SetDryRun(v bool) *SyncRunCreate {
	_c.mutation.SetDryRun(v)
	return _c
}

// SetNillableDryRun sets the "dry_run" field if the given value is not nil.
func (_c *SyncRunCreate) SetNillableDryRun(v *bool) *SyncRunCreate {
	if v != nil {
		_c.SetDryRun(*v)
	}
	return _c
}

// Mutation returns the SyncRunMutation object of the builder.
func (_c *SyncRunCreate) Mutation() *SyncRunMutation {
	return _c.mutation
}

// Save creates the SyncRun in the database.
func (_c *SyncRunCreate) Save(ctx context.Context) (*SyncRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncRunCreate) SaveX(ctx context.Context) *SyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncRunCreate) defaults() {
	if _, ok := _c.mutation.Source(); !ok {
		v := syncrun.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := syncrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.TotalServices(); !ok {
		v := syncrun.DefaultTotalServices
		_c.mutation.SetTotalServices(v)
	}
	if _, ok := _c.mutation.Added(); !ok {
		v := syncrun.DefaultAdded
		_c.mutation.SetAdded(v)
	}
	if _, ok := _c.mutation.Updated(); !ok {
		v := syncrun.DefaultUpdated
		_c.mutation.SetUpdated(v)
	}
	if _, ok := _c.mutation.Skipped(); !ok {
		v := syncrun.DefaultSkipped
		_c.mutation.SetSkipped(v)
	}
	if _, ok := _c.mutation.Failed(); !ok {
		v := syncrun.DefaultFailed
		_c.mutation.SetFailed(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := syncrun.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.DryRun(); !ok {
		v := syncrun.DefaultDryRun
		_c.mutation.SetDryRun(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncRunCreate) check() error {
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "SyncRun.source"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SyncRun.status"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "SyncRun.started_at"`)}
	}
	if _, ok := _c.mutation.TotalServices(); !ok {
		return &ValidationError{Name: "total_services", err: errors.New(`ent: missing required field "SyncRun.total_services"`)}
	}
	if _, ok := _c.mutation.Added(); !ok {
		return &ValidationError{Name: "added", err: errors.New(`ent: missing required field "SyncRun.added"`)}
	}
	if _, ok := _c.mutation.Updated(); !ok {
		return &ValidationError{Name: "updated", err: errors.New(`ent: missing required field "SyncRun.updated"`)}
	}
	if _, ok := _c.mutation.Skipped(); !ok {
		return &ValidationError{Name: "skipped", err: errors.New(`ent: missing required field "SyncRun.skipped"`)}
	}
	if _, ok := _c.mutation.Failed(); !ok {
		return &ValidationError{Name: "failed", err: errors.New(`ent: missing required field "SyncRun.failed"`)}
	}
	return nil
}

func (_c *SyncRunCreate) sqlSave(ctx context.Context) (*SyncRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncRunCreate) createSpec() (*SyncRun, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncrun.Table, sqlgraph.NewFieldSpec(syncrun.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(syncrun.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(syncrun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(syncrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(syncrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.TotalServices(); ok {
		_spec.SetField(syncrun.FieldTotalServices, field.TypeInt, value)
		_node.TotalServices = value
	}
	if value, ok := _c.mutation.Added(); ok {
		_spec.SetField(syncrun.FieldAdded, field.TypeInt, value)
		_node.Added = value
	}
	if value, ok := _c.mutation.Updated(); ok {
		_spec.SetField(syncrun.FieldUpdated, field.TypeInt, value)
		_node.Updated = value
	}
	if value, ok := _c.mutation.Skipped(); ok {
		_spec.SetField(syncrun.FieldSkipped, field.TypeInt, value)
		_node.Skipped = value
	}
	if value, ok := _c.mutation.Failed(); ok {
		_spec.SetField(syncrun.FieldFailed, field.TypeInt, value)
		_node.Failed = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(syncrun.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.DryRun(); ok {
		_spec.SetField(syncrun.FieldDryRun, field.TypeBool, value)
		_node.DryRun = value
	}
	return _node, _spec
}

// SyncRunCreateBulk is the builder for creating many SyncRun entities in bulk.
type SyncRunCreateBulk struct {
	config
	err      error
	builders []*SyncRunCreate
}

// Save creates the SyncRun entities in the database.
func (_c *SyncRunCreateBulk) Save(ctx context.Context) ([]*SyncRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncRunCreateBulk) SaveX(ctx context.Context) []*SyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
