// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"synapse/ent/tempaccess"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TempAccessCreate is the builder for creating a TempAccess entity.
type TempAccessCreate struct {
	config
	mutation *TempAccessMutation
	hooks    []Hook
}

// SetIP sets the "ip" field.
func (_c *TempAccessCreate) SetIP(v string) *TempAccessCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *TempAccessCreate) SetReason(v string) *TempAccessCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *TempAccessCreate) SetNillableReason(v *string) *TempAccessCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *TempAccessCreate) SetExpiresAt(v time.Time) *TempAccessCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TempAccessCreate) SetCreatedAt(v time.Time) *TempAccessCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TempAccessCreate) SetStatus(v string) *TempAccessCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TempAccessCreate) SetNillableStatus(v *string) *TempAccessCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// Mutation returns the TempAccessMutation object of the builder.
func (_c *TempAccessCreate) Mutation() *TempAccessMutation {
	return _c.mutation
}

// Save creates the TempAccess in the database.
func (_c *TempAccessCreate) Save(ctx context.Context) (*TempAccess, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TempAccessCreate) SaveX(ctx context.Context) *TempAccess {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempAccessCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempAccessCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TempAccessCreate) defaults() {
	if _, ok := _c.mutation.Reason(); !ok {
		v := tempaccess.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := tempaccess.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TempAccessCreate) check() error {
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "TempAccess.ip"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "TempAccess.reason"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "TempAccess.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TempAccess.created_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TempAccess.status"`)}
	}
	return nil
}

func (_c *TempAccessCreate) sqlSave(ctx context.Context) (*TempAccess, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TempAccessCreate) createSpec() (*TempAccess, *sqlgraph.CreateSpec) {
	var (
		_node = &TempAccess{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tempaccess.Table, sqlgraph.NewFieldSpec(tempaccess.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(tempaccess.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(tempaccess.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(tempaccess.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tempaccess.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tempaccess.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	return _node, _spec
}

// TempAccessCreateBulk is the builder for creating many TempAccess entities in bulk.
type TempAccessCreateBulk struct {
	config
	err      error
	builders []*TempAccessCreate
}

// Save creates the TempAccess entities in the database.
func (_c *TempAccessCreateBulk) Save(ctx context.Context) ([]*TempAccess, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TempAccess, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TempAccessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TempAccessCreateBulk) SaveX(ctx context.Context) []*TempAccess {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TempAccessCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TempAccessCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
