// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"synapse/ent/predicate"
	"synapse/ent/tempaccess"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TempAccessDelete is the builder for deleting a TempAccess entity.
type TempAccessDelete struct {
	config
	hooks    []Hook
	mutation *TempAccessMutation
}

// Where appends a list predicates to the TempAccessDelete builder.
func (_d *TempAccessDelete) Where(ps ...predicate.TempAccess) *TempAccessDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TempAccessDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TempAccessDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TempAccessDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(tempaccess.Table, sqlgraph.NewFieldSpec(tempaccess.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TempAccessDeleteOne is the builder for deleting a single TempAccess entity.
type TempAccessDeleteOne struct {
	_d *TempAccessDelete
}

// Where appends a list predicates to the TempAccessDelete builder.
func (_d *TempAccessDeleteOne) Where(ps ...predicate.TempAccess) *TempAccessDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TempAccessDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{tempaccess.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TempAccessDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
