// Code generated by ent, DO NOT EDIT.

package monitor

import (
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldName, v))
}

// ServiceName applies equality check predicate on the "service_name" field. It's identical to ServiceNameEQ.
func ServiceName(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldServiceName, v))
}

// MonitorType applies equality check predicate on the "monitor_type" field. It's identical to MonitorTypeEQ.
func MonitorType(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMonitorType, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldURL, v))
}

// DockerContainer applies equality check predicate on the "docker_container" field. It's identical to DockerContainerEQ.
func DockerContainer(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldDockerContainer, v))
}

// KumaID applies equality check predicate on the "kuma_id" field. It's identical to KumaIDEQ.
func KumaID(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldKumaID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldName, v))
}

// ServiceNameEQ applies the EQ predicate on the "service_name" field.
func ServiceNameEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldServiceName, v))
}

// ServiceNameNEQ applies the NEQ predicate on the "service_name" field.
func ServiceNameNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldServiceName, v))
}

// ServiceNameIn applies the In predicate on the "service_name" field.
func ServiceNameIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldServiceName, vs...))
}

// ServiceNameNotIn applies the NotIn predicate on the "service_name" field.
func ServiceNameNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldServiceName, vs...))
}

// ServiceNameGT applies the GT predicate on the "service_name" field.
func ServiceNameGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldServiceName, v))
}

// ServiceNameGTE applies the GTE predicate on the "service_name" field.
func ServiceNameGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldServiceName, v))
}

// ServiceNameLT applies the LT predicate on the "service_name" field.
func ServiceNameLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldServiceName, v))
}

// ServiceNameLTE applies the LTE predicate on the "service_name" field.
func ServiceNameLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldServiceName, v))
}

// ServiceNameContains applies the Contains predicate on the "service_name" field.
func ServiceNameContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldServiceName, v))
}

// ServiceNameHasPrefix applies the HasPrefix predicate on the "service_name" field.
func ServiceNameHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldServiceName, v))
}

// ServiceNameHasSuffix applies the HasSuffix predicate on the "service_name" field.
func ServiceNameHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldServiceName, v))
}

// ServiceNameEqualFold applies the EqualFold predicate on the "service_name" field.
func ServiceNameEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldServiceName, v))
}

// ServiceNameContainsFold applies the ContainsFold predicate on the "service_name" field.
func ServiceNameContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldServiceName, v))
}

// MonitorTypeEQ applies the EQ predicate on the "monitor_type" field.
func MonitorTypeEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMonitorType, v))
}

// MonitorTypeNEQ applies the NEQ predicate on the "monitor_type" field.
func MonitorTypeNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldMonitorType, v))
}

// MonitorTypeIn applies the In predicate on the "monitor_type" field.
func MonitorTypeIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldMonitorType, vs...))
}

// MonitorTypeNotIn applies the NotIn predicate on the "monitor_type" field.
func MonitorTypeNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldMonitorType, vs...))
}

// MonitorTypeGT applies the GT predicate on the "monitor_type" field.
func MonitorTypeGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldMonitorType, v))
}

// MonitorTypeGTE applies the GTE predicate on the "monitor_type" field.
func MonitorTypeGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldMonitorType, v))
}

// MonitorTypeLT applies the LT predicate on the "monitor_type" field.
func MonitorTypeLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldMonitorType, v))
}

// MonitorTypeLTE applies the LTE predicate on the "monitor_type" field.
func MonitorTypeLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldMonitorType, v))
}

// MonitorTypeContains applies the Contains predicate on the "monitor_type" field.
func MonitorTypeContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldMonitorType, v))
}

// MonitorTypeHasPrefix applies the HasPrefix predicate on the "monitor_type" field.
func MonitorTypeHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldMonitorType, v))
}

// MonitorTypeHasSuffix applies the HasSuffix predicate on the "monitor_type" field.
func MonitorTypeHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldMonitorType, v))
}

// MonitorTypeEqualFold applies the EqualFold predicate on the "monitor_type" field.
func MonitorTypeEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldMonitorType, v))
}

// MonitorTypeContainsFold applies the ContainsFold predicate on the "monitor_type" field.
func MonitorTypeContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldMonitorType, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldURL, v))
}

// URLIsNil applies the IsNil predicate on the "url" field.
func URLIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldURL))
}

// URLNotNil applies the NotNil predicate on the "url" field.
func URLNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldURL))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldURL, v))
}

// DockerContainerEQ applies the EQ predicate on the "docker_container" field.
func DockerContainerEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldDockerContainer, v))
}

// DockerContainerNEQ applies the NEQ predicate on the "docker_container" field.
func DockerContainerNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldDockerContainer, v))
}

// DockerContainerIn applies the In predicate on the "docker_container" field.
func DockerContainerIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldDockerContainer, vs...))
}

// DockerContainerNotIn applies the NotIn predicate on the "docker_container" field.
func DockerContainerNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldDockerContainer, vs...))
}

// DockerContainerGT applies the GT predicate on the "docker_container" field.
func DockerContainerGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldDockerContainer, v))
}

// DockerContainerGTE applies the GTE predicate on the "docker_container" field.
func DockerContainerGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldDockerContainer, v))
}

// DockerContainerLT applies the LT predicate on the "docker_container" field.
func DockerContainerLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldDockerContainer, v))
}

// DockerContainerLTE applies the LTE predicate on the "docker_container" field.
func DockerContainerLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldDockerContainer, v))
}

// DockerContainerContains applies the Contains predicate on the "docker_container" field.
func DockerContainerContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldDockerContainer, v))
}

// DockerContainerHasPrefix applies the HasPrefix predicate on the "docker_container" field.
func DockerContainerHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldDockerContainer, v))
}

// DockerContainerHasSuffix applies the HasSuffix predicate on the "docker_container" field.
func DockerContainerHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldDockerContainer, v))
}

// DockerContainerIsNil applies the IsNil predicate on the "docker_container" field.
func DockerContainerIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldDockerContainer))
}

// DockerContainerNotNil applies the NotNil predicate on the "docker_container" field.
func DockerContainerNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldDockerContainer))
}

// DockerContainerEqualFold applies the EqualFold predicate on the "docker_container" field.
func DockerContainerEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldDockerContainer, v))
}

// DockerContainerContainsFold applies the ContainsFold predicate on the "docker_container" field.
func DockerContainerContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldDockerContainer, v))
}

// KumaIDEQ applies the EQ predicate on the "kuma_id" field.
func KumaIDEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldKumaID, v))
}

// KumaIDNEQ applies the NEQ predicate on the "kuma_id" field.
func KumaIDNEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldKumaID, v))
}

// KumaIDIn applies the In predicate on the "kuma_id" field.
func KumaIDIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldKumaID, vs...))
}

// KumaIDNotIn applies the NotIn predicate on the "kuma_id" field.
func KumaIDNotIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldKumaID, vs...))
}

// KumaIDGT applies the GT predicate on the "kuma_id" field.
func KumaIDGT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldKumaID, v))
}

// KumaIDGTE applies the GTE predicate on the "kuma_id" field.
func KumaIDGTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldKumaID, v))
}

// KumaIDLT applies the LT predicate on the "kuma_id" field.
func KumaIDLT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldKumaID, v))
}

// KumaIDLTE applies the LTE predicate on the "kuma_id" field.
func KumaIDLTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldKumaID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.NotPredicates(p))
}
