// Code generated by ent, DO NOT EDIT.

package autheliaalert

import (
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldID, id))
}

// Cname applies equality check predicate on the "cname" field. It's identical to CnameEQ.
func Cname(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldCname, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldMessage, v))
}

// Severity applies equality check predicate on the "severity" field. It's identical to SeverityEQ.
func Severity(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldSeverity, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// CnameEQ applies the EQ predicate on the "cname" field.
func CnameEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldCname, v))
}

// CnameNEQ applies the NEQ predicate on the "cname" field.
func CnameNEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldCname, v))
}

// CnameIn applies the In predicate on the "cname" field.
func CnameIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldCname, vs...))
}

// CnameNotIn applies the NotIn predicate on the "cname" field.
func CnameNotIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldCname, vs...))
}

// CnameGT applies the GT predicate on the "cname" field.
func CnameGT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldCname, v))
}

// CnameGTE applies the GTE predicate on the "cname" field.
func CnameGTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldCname, v))
}

// CnameLT applies the LT predicate on the "cname" field.
func CnameLT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldCname, v))
}

// CnameLTE applies the LTE predicate on the "cname" field.
func CnameLTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldCname, v))
}

// CnameContains applies the Contains predicate on the "cname" field.
func CnameContains(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContains(FieldCname, v))
}

// CnameHasPrefix applies the HasPrefix predicate on the "cname" field.
func CnameHasPrefix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasPrefix(FieldCname, v))
}

// CnameHasSuffix applies the HasSuffix predicate on the "cname" field.
func CnameHasSuffix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasSuffix(FieldCname, v))
}

// CnameEqualFold applies the EqualFold predicate on the "cname" field.
func CnameEqualFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEqualFold(FieldCname, v))
}

// CnameContainsFold applies the ContainsFold predicate on the "cname" field.
func CnameContainsFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContainsFold(FieldCname, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContainsFold(FieldMessage, v))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldSeverity, vs...))
}

// SeverityGT applies the GT predicate on the "severity" field.
func SeverityGT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldSeverity, v))
}

// SeverityGTE applies the GTE predicate on the "severity" field.
func SeverityGTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldSeverity, v))
}

// SeverityLT applies the LT predicate on the "severity" field.
func SeverityLT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldSeverity, v))
}

// SeverityLTE applies the LTE predicate on the "severity" field.
func SeverityLTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldSeverity, v))
}

// SeverityContains applies the Contains predicate on the "severity" field.
func SeverityContains(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContains(FieldSeverity, v))
}

// SeverityHasPrefix applies the HasPrefix predicate on the "severity" field.
func SeverityHasPrefix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasPrefix(FieldSeverity, v))
}

// SeverityHasSuffix applies the HasSuffix predicate on the "severity" field.
func SeverityHasSuffix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasSuffix(FieldSeverity, v))
}

// SeverityEqualFold applies the EqualFold predicate on the "severity" field.
func SeverityEqualFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEqualFold(FieldSeverity, v))
}

// SeverityContainsFold applies the ContainsFold predicate on the "severity" field.
func SeverityContainsFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContainsFold(FieldSeverity, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AutheliaAlert) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AutheliaAlert) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AutheliaAlert) predicate.AutheliaAlert {
	return predicate.AutheliaAlert(sql.NotPredicates(p))
}
