// Code generated by ent, DO NOT EDIT.

package tempaccess

import (
	"synapse/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldID, id))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldIP, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldReason, v))
}

// AutheliaInstanceID applies equality check predicate on the "authelia_instance_id" field. It's identical to AutheliaInstanceIDEQ.
func AutheliaInstanceID(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldAutheliaInstanceID, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldCreatedAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldStatus, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasSuffix(FieldIP, v))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContainsFold(FieldIP, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContainsFold(FieldReason, v))
}

// AutheliaInstanceIDEQ applies the EQ predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDEQ(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldAutheliaInstanceID, v))
}

// AutheliaInstanceIDNEQ applies the NEQ predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDNEQ(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldAutheliaInstanceID, v))
}

// AutheliaInstanceIDIn applies the In predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDIn(vs ...int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldAutheliaInstanceID, vs...))
}

// AutheliaInstanceIDNotIn applies the NotIn predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDNotIn(vs ...int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldAutheliaInstanceID, vs...))
}

// AutheliaInstanceIDGT applies the GT predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDGT(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldAutheliaInstanceID, v))
}

// AutheliaInstanceIDGTE applies the GTE predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDGTE(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldAutheliaInstanceID, v))
}

// AutheliaInstanceIDLT applies the LT predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDLT(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldAutheliaInstanceID, v))
}

// AutheliaInstanceIDLTE applies the LTE predicate on the "authelia_instance_id" field.
func AutheliaInstanceIDLTE(v int) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldAutheliaInstanceID, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldCreatedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TempAccess {
	return predicate.TempAccess(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TempAccess) predicate.TempAccess {
	return predicate.TempAccess(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TempAccess) predicate.TempAccess {
	return predicate.TempAccess(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TempAccess) predicate.TempAccess {
	return predicate.TempAccess(sql.NotPredicates(p))
}
