// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AutheliaAlert is the predicate function for autheliaalert builders.
type AutheliaAlert func(*sql.Selector)

// AutheliaInstance is the predicate function for autheliainstance builders.
type AutheliaInstance func(*sql.Selector)

// DockerEvent is the predicate function for dockerevent builders.
type DockerEvent func(*sql.Selector)

// KumaInstance is the predicate function for kumainstance builders.
type KumaInstance func(*sql.Selector)

// Monitor is the predicate function for monitor builders.
type Monitor func(*sql.Selector)

// NPMInstance is the predicate function for npminstance builders.
type NPMInstance func(*sql.Selector)

// ServiceLink is the predicate function for servicelink builders.
type ServiceLink func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// SyncRun is the predicate function for syncrun builders.
type SyncRun func(*sql.Selector)

// TempAccess is the predicate function for tempaccess builders.
type TempAccess func(*sql.Selector)
