// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Monitor is the predicate function for monitor builders.
type Monitor func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// SyncRun is the predicate function for syncrun builders.
type SyncRun func(*sql.Selector)
